// Autogenerated with DRAKON Editor 1.27

public class SnakeGame {

    void SnakeGame() {
        // item 19
        lib_init();
        // item 20
        render();
        while (true) {
            // item 21
            input();
            // item 24
            update();
            // item 22
            if (gameover) {
                break;
            } else {
                
            }
            // item 26
            render();
            // item 25
            delay();
        }
        // item 23
        bye();
    }

    void lib_init() {
        // item 60
        lib_init();
        // item 61
        create_window();
        // item 62
        load_textures();
        // item 63
        clear_tails();
        // item 65
        init_snake();
        // item 64
        init_fruit();
        // item 66
        set_direction();
    }

    void render() {
        // item 81
        if (snake_len > 0) {
            // item 84
            draw_body();
        } else {
            
        }
        // item 85
        if (eaten) {
            // item 88
            draw_fruit();
        } else {
            // item 89
            clear_tail();
        }
        // item 90
        draw_head();
    }
}
