-*- mode: org; fill-column: 95 -*-
@title Emacs Code Browser - Emacs как IDE
@category emacs
@sort emacs001

* Инсталляция

Добавляем в CEDET EmacsCodeBrowser, который превращает emacs в
многоязыковую IDE.

Берем снапшот из <a href="http://ecb.sourceforge.net/cvs_snapshots/ecb.tar.gz">официального
репозитория</a> и распаковываем в <code>~/.emacs.d/ecb</code>

* Конфигурирование

Добавляем в конфиграционный файл Емакса следующие строчки:
<source lang="lisp">
;; Load ECB
(add-to-list 'load-path "~/.emacs.d/ecb")
(require 'ecb-autoloads)
(global-set-key (kbd "C-x p") 'ecb-activate)
(global-set-key (kbd "C-x j") 'ecb-deactivate)
(global-set-key (kbd "C-x ,") 'ecb-toggle-ecb-windows)
(global-set-key (kbd "\e\eg") 'goto-line)
(global-set-key [?\M-g] 'goto-line)
(define-key global-map (kbd "C-<tab>") 'workspace-controller)
(setq ecb-tip-of-the-day nil)
(setq ecb-prescan-directories-for-emptyness nil)
</source>
После этого перезапускаем Емакс и даем команду <code>M-x ecb-byte-compile</code>,
которая ускорит загрузку нашей среды программирования.

Теперь, чтобы запустить ECB можно нажать <code>C-x p</code> А чтобы скрыть <code>C-x</code> ,
Ну а если вы хотите вообще выключить ECB - <code>C-x j</code> При желании вы можете настроить свои
комбинации клавиш.

Продуктивной работы!
