#+STARTUP: showall indent hidestars

* Установка необходимого
** Установка JDK
Скачать Java SE Dev Kit 8 (принять соглашение)
http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html
Добавить пути.
*** Windows
Панель управлнения / Система и безопасность / Система
ссылка: Дополнительные параметры
кнопка: Переменные среды
Блок "Системные переменные"
Добавить "JAVA_HOME" с путем к JDK
=Скриншот java_home.png=
*** Linux:
**** Распаковать в какую-нибудь папку

#+BEGIN_SRC sh
  tar xvfz jdk-9_linux-x64_bin.tar.gz
#+END_SRC

**** Прописать этот путь в ~/.profile:

#+BEGIN_SRC sh
  export JAVA_HOME=/usr/lib/jvm/java-9-openjdk-amd64
  export PATH=$PATH:$JAVA_HOME/bin
#+END_SRC

** Установка IntelliJ IDEA
Устанавливаем бесплатную Community версию
https://www.jetbrains.com/idea/download/#section=linux
** Создание первого проекта - Hello World
Новый проект / Java
Указать путь к JDK
#+BEGIN_SRC java
     public class Main {
         public static void main(String[] args) {
             System.out.println("Hello");
         }
     }
#+END_SRC
И запускаем его из среды.
** Скачиваем графическую библиотеку

http://libgdx.badlogicgames.com/download.html

Запускаем. Это мастер создания проекта

Получится кроссплатформенный проект, но мы пока убираем все галочки кроме ~Desktop~

Генерация проекта подтягивает все необходимые библиотеки и генерирует проект в той
папке, где запущена.

** Открываем проект в Idea

Импортировать проект найдя его папку и в ней файл ~build.gradle~

При импорте снимаем галочку ~Create separate module per source set~

Нажимаем "ОК"

** Настройка проекта

Настроим Run->Edit Configuration

Нажимаем "+"

Нам нужно обычное приложение "Application"

Здесь нужно поменять 4 пункта:
- Name (название файла запускающего приложение) - DeskApp
- MainClass (отсюда стартует код приложения) - указываем DesktopLauncher
- Working Directory (рабочая папка где лежат файлы используемые
  приложением) ./core/assets
- Use classpath or module - выбрать desktop - это папка где лежит DesktopLauncher
- Use (desktop)
- JRE
  Запускаем через меню Run

** Модифицируем проект

Меняем размеры окна

Картинки будут лежать в папке assets

** Выводим картинку на экран

и экспериментируем
