-*- mode: org; fill-column: 95 -*-
@title Установка и настройка SBCL.

* Установка

 SBCL - Это Steel Bank Common Lisp, наиболее продвинутая в техническом отношении реализация
 Common Lisp. А Common Lisp - наиболее продвинутый в техническом отношении язык
 программирования. Поэтому без него мы не обойдемся. Также для интеграции с Емаксом нам
 подадобиться SLIME и SWANK - эти компоненты связывают EMACS и SBCL воедино

<source lang="bash">
$ sudo apt-get install sbcl slime cl-swank
</source>

* Настройка

 На самом деле для серьезного программирования на лиспе лучше все эти вещи ставить сильно
 вручную, в зависимости от ваших задач, но для старта подойдет и упрощенный вариант. Вот что мы
 прописываем в init.el:

<source lang="lisp">
;;SBCL
(setq slime-lisp-implementations '((sbcl ("sbcl"))))
(setq slime-startup-animation nil)
;; Путь к локльной копии Common Lisp Hyper Specifications.
;; Если его не задавать - справка по функциям будет загружать страницы из интернета
;; (setq common-lisp-hyperspec-root "file:///Users/lisp/HyperSpec")

;; SLIME
(add-to-list 'load-path "~/.emacs.d/slime") ;; Путь к slime
(require 'slime)
(setq slime-net-coding-system 'utf-8-unix)
(slime-setup '(slime-fancy))
</source>
