-*- mode: org; fill-column: 95 -*-
@title About

Я Rigidus, а это мой хомяк. Хомяк — страшная сила. Раньше, когда этот хомяк был белым и
хостился на мастерхосте и был написан, страшно сказать, на php, я сослался с него на свой
старый блог. Это была роковая ошибка. Пришли спаммеры..

Капча не помогла, пришлось все заморозить и отключить нахрен все комментарии. Livejournal тоже
подкузьмил: сначала они вставили рекламу — я терпел. Потом придумали свои "кирилические
сервисы" — я терпел. Но пара десятков комментариев с порнухой в день — это извините
перебор. Назрела необходимость переезжать..

* Happy new Year

  И тут случился Новый Год 2011. А новый год - это, знаете ли такое время, когда настоящий
  программист одинок, грустит и сидит за компьютером. Так что я как минимум на ⅓ настоящий
  программист, вернее был им 31-ого декабря 2010.

  И тут я подумал: «Доколе!». Почему в то время, как я на работе пишу на лучшем из языков
  программирования мой хомяк написан, стыдно сказать на чем! Коллеги не поймут! В общем, было
  принято решение все менять. <s>Флаг, герб и гимн.</s> Так мой хомяк в новогоднюю ночь стал
  черным, злым и приготовился противостоять хабраэффекту.

  Хабраэффект был выдержан без особых проблем - и действительно, компиляция в машинный код и
  ключевые данные в памяти творят чудеса в отношении производительности. Я окончательно поверил
  в то, что язык, более чем с 50-летней историей не может быть плохим!

  Этот год я провел изучая и используя Common Lisp на полную катушку. Мои волосы стали гладкими
  и шелковистыми, настроение улучшилось и я стал проводить на работе меньше времени. Впрочем,
  все это вранье :) На самом деле я стал работать только больше - исключительно потому что
  используя Common Lisp я стал работать с большим удовольствием. Прощайте невыразительные и
  скучные языки, рефакторинг которых напоминает операцию на гландах, проводимую автогеном через
  задний проход. Да здравствует производительность, выразительная сила и мощь макросов Common
  Lisp!

  С Новым 2012 годом!

* Работа

  Я работаю уже во второй по счету компании, которая платит мне за то, что я пишу веб-решения
  на Common Lisp. И не только за это. Я искренне считаю, что руководитель должен понимать
  предметную область, которой он руководит. Мне приходилось настраивать сервера, писать сложные
  веб-приложения, интегрироваться с платежками, картографическими сервисами и веб-сервисами
  продажи билетов и формализовывать сложные и запутанные бизнес-процессы и теперь я точно знаю,
  что если любой человек, работающий в моей команде не справится со своей задачей - я смогу
  сесть и все исправить. Это дает невероятное чувство уверенности в будущем любых проектов.

  До этого я писал на PHP, Python, C/C++, Java, Delphi/Pascal, Assembler80x86, Forth. Но нигде
  и никогда я не видел такой выразительной силы и удобства в поддержке кода. Используя Common
  Lisp я делаю больше за гораздо меньшее время.

