
OpenCog — инструмент для создания искусственного интеллекта на основе
открытого исходного кода.

* Что такое OpenCog

  OpenCog - open source Artificial General Intelligence framework, с
  целью проявить общий интеллект уровня человека и за его пределами.

  Т.е. "Мы предпринимаем серьезные усилия, направленные на построение
  думающей машины."

  А также: "У нас есть детальный план и возможность ее выполнить, и мы
  осуществляем его благодаря жесткой работы шаг за шагом"

  Суть задачи: "Мы не занимаемся созданием программы, которая делает
  одну конкретную задачу, такие как игра в шахматы, диагностика
  заболевания, или вождение автомобиля. Мы озабочены общим интеллектом
  и взаимосвязанными когнитивными процессами, которые он влечет за собой."

* Разработчики

  - Команда в Гонконге, работающих на применении OpenCog для
    управления интеллектуальными игровыми персонажами
  - Несколько разработчиков в США, Европе и Гонконге, работающих на
    различных работодателей и применяющих OpenCog в коммерческих и
    государственных проектах;
  - Пять Google Summer of Code 2012 студентов, работающих на OpenCog;
    Некоторые фантастические добровольцы-разработчики.

* Детали

  =OpenCog=, в качестве программной основы, направлен на обеспечение
  ученых и разработчиков программного обеспечения общей платформы для
  создания и обменом программами искусственного
  интеллекта. Долгосрочной целью OpenCog является ускорение развития
  взаимовыгодного AGI.

  =OpenCogPrime= является специфическим AGI дизайном, который строится
  в рамках OpenCog framework. Он поставляется как довольно подробный,
  комплексный проект, охватывающий все аспекты интеллекта. Гипотеза
  заключается в том, что если этот проект будет полностью реализован и
  опробован на разумного размера распределенной сети, результат будет
  AGI системой с общим интеллектом на уровне человека и, в конечном
  итоге за его пределами.

** Части =OpenCog= проекта

   - =OpenCog Framework (OCF)= предоставляет собой похожую на ОС
     инфраструктуру и стабильного API, и включает в себя компоненты,
     написанные на =C++ Templates= и =Boost=:
     - =AtomSpace= разделяемая библиотека для быстрого представления
       знаний в памяти, обеспечивает гибридные структуры данных для
       интеграции и управления когнитивными и символьными знаниями.
     - =CogServer= контейнер и планировщик для подключаемых когнитивных
       алгоритмов
   - Различные OpenCog проекты, которые используют или связаны с OCF, в
     том числе
     - Когнитивный подключаемый алгоритм =MOSES=, =PLN= и другие;
     - Интерфейсы и прокси-серверы, например =CogBot=, интерфейс для
     - =OpenSim=
     - Комплексная обработка естественного языка, вместе с его
       самостоятельными, но тесно сочетающимися проектами, например =RelEx=
       и =Link Grammar=
     - =Embodiment= содержит код для подключения ОС к виртуальным мирам и
       созданию виртуального питомца и гуманоидного агента

* Спонсоры

  - =Фонд Singularity Institute for Artificial Intelligence= является
    основным спонсором и источником финансирования.
  - =Novamente LLC= является спонсором, основными источником кадров и
    других ресурсов.
  - =Google Inc.= обеспечивает финансовую поддержку для OpenCog
    программистов через Google Summer of Code в 2008 и 2009 годах.
  - =Xiamen= университет, Китай сделал некоторые работы по OpenCog в
    2009-2011 годах финансируемое китайским правительством.
  - Фонд =Hong Kong SAR's Innovation and Technology= и Гонконгский
    политехнический университет (Hong Kong Polytechnic University).

* Фонд OpenCog

  OpenCog является open-source проектом, а не формальной организацией. А
  также некоммерческая организация OpenCog Foundation, в частности,
  посвящена содействию исследованиям и разработкам OpenCog.

* Участникам

  - OpenCog список адресов электронной почты, в группе Google
    https://groups.google.com/forum/?fromgroups#!overview
  - Скачать OpenCog в Github
    https://github.com/opencog/opencog
  - Сборка OpenCog, т.е. компиляция исходного кода.
    http://wiki.opencog.org/w/Building_OpenCog
  - Начало работы с OpenCog для разработчиков
    http://wiki.opencog.org/w/Getting_Started
  - IRC канал OpenCog на freenode #opencog… используйте ваш любимый
    IRC-клиент или IRC.freenode.net
    http://webchat.freenode.net/?channels=opencog

* Новости

  Есть два источника новостей о OpenCog проекте:

  - Блог OpenCog Brainwave, время от времни участники OpenCog
    рассказывают об их технических работах, которые в процессе или
    завершены;
    http://blog.opencog.org/
  - OpenCog Foundation News — RSS новости от сайта организации OpenCog
    фонда.
    http://opencog.org/feed/



* Техническая и научная информация

  - Краткий обзор OpenCog разработки программного обеспечения.
    http://wiki.opencog.org/w/Development
  - Глоссарий OpenCog терминов.
    http://wiki.opencog.org/w/OpenCogGlossary
  - Primer on OpenCog Node and Link types, краткий обзор OpenCog
    текущего явного языка представления знаний.
    http://wiki.opencog.org/w/OpenCogAtomTypes
  - Обзорная бумага, описывая CogPrime дизайн для продвинутых AGI,
    благодаря чему OpenCog codebase в настоящее время частично
    реализуется.
    http://wiki.opencog.org/w/CogPrime_Overview
  - Проект wikibook на OpenCog Prime AGI дизайн, будет устаревшим до
    тех пор пока книга Building Better Minds, наконец, не выйдет в
    конце 2012 года. Заметьте, это содержит несколько устаревший
    материал и не всегда удобно. Новичкам, вместо этого, рекомендуется
    ознакомиться с CogPrime Overview. Но Wikibook содержит более
    глубокое и детальное описание.
    http://wiki.opencog.org/w/OpenCogPrime:WikiBook
  - Список Идей для будущего развития, и перечень Проектных
    Предложений (нет веской причины, почему это две отдельных
    страницы, но в настоящее время так исторически сложилось).
    http://wiki.opencog.org/w/Ideas
    http://wiki.opencog.org/w/OpenCogPrime:Design_Suggestions
  - Список связанных с OpenCog публикаций, что несколько
    устарели.
    http://opencog.org/research/
  - См. также страницу издания Бена Герцеля (Ben
    Goertzel's), которая имеет много связанных с OpenCog публикаций.
    http://wp.goertzel.org/?page_id=22


* CogBuntu


  CogBuntu — это ремикс-версия Ubuntu Linux, которая включает в себя все
  OpenCog основные компоненты (плюс все необходимые зависимости, такие
  как библиотеки, инструменты и т.д.) предварительно установленные,
  предварительно настроенные и готовые к работе!


* Концепции

** Гиперграф

   Гиперграф это расширение обычной концепции графа, позволяющей ребру
   графа иметь более 2-х вершин. HyperGraphDB расширяет эту концепцию еще
   больше:
   - позволяя ребру указывать на другое ребро,
   - позволяет любому ребру или вершине иметь произвольное значение в
     виде полезной нагрузки.

** Атом

   Основная единица хранения в называется atom. Каждый atom имеет
   произвольное значение и может указывать любое количество других
   atom.

* Что читать

  - Что такое OpenCog и зачем: https://habrahabr.ru/post/160255/
  - Основы подхода к построению универсального интеллекта:
    https://geektimes.ru/post/145309/
    https://geektimes.ru/post/145467/
  - «Непредвзятый» универсальный алгоритмический интеллект
    https://geektimes.ru/post/150056/
    https://geektimes.ru/post/150902/
  - Когнитивное смещение универсального интеллекта
    https://geektimes.ru/post/151838/
  - Нейробиология и искусственный интеллект
    http://habrahabr.ru/post/151628/
    http://habrahabr.ru/post/151739/
    https://geektimes.ru/post/151890/
  - Искусственный интеллект как совокупность вопросов
    https://habrahabr.ru/post/151102/
  - Алгоритмическая неразрешимость – это не препятствие для
    алгоритмического ИИ
    https://geektimes.ru/post/145929/
  - Модель функционального разделения сознания и бессознательного
