#+TITLE: PHP. Как прикрутить OpenID сервер

В словаре веб-программистов есть специфическое слово
"прикрутить". Когда нужно найти инфу по незнакомой теме, такой,
например, как "OpenID", первое что делает программист - лезет в
гугль. Обычный программист набирает что-то вроде "OpenID
specification". Наш программист не хочет читать спецификации, он хочет
сразу, быстро, и желательно по-русски. Поэтому его запрос примерно
такой: "PHP OpenID прикрутить". Для того, чтобы облегчить жизнь такому
программисту я и написал этот абзац.

* OpenID по русски

Итак, стоит задача - у себя на хостинге сделать OpenID-сервер, чтобы
можно было оставлять комментарии в различных блогах, используя как
удостоверение своей личности свой сайт (на котором может быть блог, а
может и не быть). Прочтение спецификации не приводит к просветлению,
но все-же имеет смысл:

<a href="http://ru.wikipedia.org/wiki/OpenID">
  http://ru.wikipedia.org/wiki/OpenID
</a> - на русском
<a href="http://openid.net/specs/openid-authentication-2_0.html">
  http://openid.net/specs/openid-authentication-2_0.html
</a> - спецификация

* Ресурсы

Традиционно обращаемся к блогам за критикой спецификаций и
дополнительной информацией:

Этот человек внес струю свежего воздуха в мой воспаленный мозг :)
Нашел много полезного, например:
http://david-m.livejournal.com/760821.html - это реализованный
OpenID-consumer, т.е. сервис, проверяющий идентификацию - им удобно
отлаживать свой OpenID сервер.  <a
href="http://david-m.livejournal.com/tag/openid">ЖЖ Давида
Мзареуляна</a> (записи с тегом OpenId)

Запись в блоге МакСима, которая будет интересна пользователям
мастерхоста (я один из них), у которых PHP скомпилирован без поддержки
CURL.  <a
href="http://mak-sim.ru/2007/02/28/95">http://mak-sim.ru/2007/02/28/95</a>

Сценарий раскрытия пароля при использовании OpenId от <lj
user="mderk"> <a
href="http://www.ragbag.ru/2007/01/21/openid_phishing/">http://www.ragbag.ru/2007/01/21/openid_phishing/</a>

Иван Сагалаев, хоть пишет и не на PHP - зато разумно и по
делу. Затрагиваются и смежные области. Много хороших идей, которые
<s>так хочется спиздить</s> нуждаются в разработке.  <a
href="http://softwaremaniacs.org/blog/2007/03/25/cicero-openid-hcard/">http://softwaremaniacs.org/blog/2007/03/25/cicero-openid-hcard/</a>
<a
href="http://softwaremaniacs.org/blog/2007/03/28/openid-mutants/">http://softwaremaniacs.org/blog/2007/03/28/openid-mutants/</a>

* Решения

Теперь, когда мы знаем все, что нам нужно про OpenID, можно приступать
к поиску готовых решений, которые можно использовать в своих
проектах. На текущий момент я нашел несколько, буду признателен, если
кто-нибудь дополнит.

<a
href="http://www.openidenabled.com/">http://www.openidenabled.com/</a>
PHP OpenID Library - (не только PHP). Выглядит монструозно, на
мастерхосте не заработала, потому что не смогла найти XML-парсер
(привет админам Мастерхоста - всерьез думаю о том, чтобы менять
хостинг).

<a
href="http://www.phpclasses.org/browse/package/3290.html">http://www.phpclasses.org/browse/package/3290.html</a>
Simple OpenID PHP Class - спасибо, Дима Смирнов. У меня не заработал,
потому что на мастерхосте PHP скомпилирован без CURL. (ненавижу!)

<a
href="http://siege.org/projects/phpMyID/">http://siege.org/projects/phpMyID/</a>
Этот проект, состоящий всего из двух небольших файлов - заработал
сразу. И действительно, многое встает на свои места при просмотре его
кода. Он использует Basic HTTP-авторизацию, что в коде выглядит очень
компактно (но если хотите можно легко заменить на привычную
веб-авторизацию). Он не требует базы данных, поддержки XML или
чего-нибудь подобного. Пожалуй, можно рекомендовать.
