#+STARTUP: showall indent hidestars

#+HTML_HEAD: <!-- -*- fill-column: 87 -*- -->
#+HTML_HEAD: <!-- org-toggle-inline-images -->

#+TITLE: Главная страница

#+INFOJS_OPT: view:overview toc:nil

#+NAME:css
#+BEGIN_HTML
<link rel="stylesheet" type="text/css" href="/css/css.css" />
#+END_HTML

Привет!

Меня зовут Глухов Михаил (Rigidus), моя специализация - компиляторы,
языки программирования, и их среды выполнения (виртуальные машины,
распределенные системы и.т.п.) В свободное время я занимаюсь
любительской робототехникой.

Здесь собраны мои статьи, ислледования, руководства и полезные
материалы. Если вас что-то заинтересовало, или у вас есть интересная
работа - свяжитесь со мной [[/contacts][-> контакты]]

Мое актуальное [[/resume][резюме]] содержит не все мои компетенции, а только те,
которые я считаю важными для абстрактного "будущего
работодателя". Возможно я ошибаюсь в том, что для него является важным
на самом деле. Но нужно как-то уложиться в формат пары страниц.

- Обо мне
  - Личная информация
  - Опыт работы
  - Исследовательский опыт
- Публикации
  - Слайды с докладов
  - Видеозаписи
  - Литературное программирование
  - Макросы в Lisp
- Проекты
  - Автоматический поиск работы
  - Система автоматизированного тестирования интерфейсов
  - Моделирование электронных схем
  - Умный гараж с нуля
  - Как написан этот сайт
- Статьи и руководства
  - Структура и интерпретация компьютерных программ
  - Ассемблер
  - Common Lisp
  - Emacs
  - Нетрадиционно ориентированная диспетчеризация
  - Немного о переназначении регистров
- Ссылки и книги
  - Как проектируются IP-блоки и системы на кристалле
  - OpenCog и гиперграфы
  - Компиляторы (книга Дракона)
