#+STARTUP: showall indent hidestars

#+HTML_HEAD: <!-- -*- fill-column: 87 -*- -->
#+HTML_HEAD: <!-- org-toggle-inline-images -->

#+TITLE: Проекты

#+INFOJS_OPT: view:overview toc:nil

#+NAME:css
#+BEGIN_HTML
<link rel="stylesheet" type="text/css" href="/css/css.css" />
#+END_HTML

** Автоматический поиск работы

Начался как шуточная попытка смоделировать борьбу программы-HR
(написанной, разумеется, на bash и использующей grep для определения
пригодности резюме) и программы на лиспе, которая представляла собой
генетический самообучающийся алгоритм выращивания такого резюме,
которое пробьет фильтр программы HR.

Всем известно, что HR необучаемы (я шучу!) поэтому чтобы было
интереснее, я добавил в программму-HR параметр "настроение" зависящий
от времени суток, дня недели и "гиковости" предыдущего резюме.

Разумеется, для того чтобы играть в такое, понадобилась база резюме и
вакансий, которая была тут же спарсена с =headhunter=.

Какого же было мое изумление, когда несколько моих друзей
действительно нашли себе работу используя эту штуку. Ну а дальше уже
мне стало интересно...

** Автоматизированное тестирование интерфейсов

Этот проект вырос из шуточной программы, (написанной (не мной) на
Common Lisp), которая умеет играть с динозавром из броузера Chrome
(который появляется когда нет подключения к интернету).

Мне понравилась идея, что можно тыкать мышкой не только внутри
броузера но и вообще везде и я решил добавить туда некоторые методы
того, что я называю "противоестественным интеллектом" (искусственным
его нельзя назвать, но и на естественный он как-то тоже не похож).

В результате появилась штука, которая ищет ошибки весьма
парадоксальным образом.

** Моделирование электронных схем

Это продолжение замечательной идеи из SICP, связанной с моделированием
распространения сигнала в графе. Интересно в первую очередь с
исследователькой стороны

** Умный гараж с нуля

Плоды моих занятий с низкоуровневым программирование микроконтроллеров

** Сам сайт

Там просто есть некоторые нетривиальные вещи. Может быть даже
настолько нетривиальные, что я на всякий случай решил их записать,
чтобы не забыть.
