#+OPTIONS: toc:nil

** Клеточные автоматы

Пожалуй надо сделать небольшую веселую статью для
популяризации этих вычислимых объектов, правила для которых
являются "множествами непрерывных эндоморфизмов в сдвиговом пространстве".

Это могло бы быть интересным на следующем ITGM и достаточно
функциональным для FProg-комьюнити. Особенно если описать все на хаскеле -
заодно хороший повод в нем наконец разобраться.

Можно было бы рассмотреть:
- "Жизнь" Конвея
- "WireWorld" Брайаном Сильверманом (особенно интересен в
  в отношении применимости к проекту симуляции электронных
  схем.
- Алгоритм волновой трассировки Ли для поиска путей
  (например, в двумерных играх, или для трассировки печатных плат,
  что даже лучше)
- "Муравей Ленгтона" и его эквивалентность машине Тьюринга
  с 2 символами и 4 состояниями
  Работа Пауля Чепмена и немного про Регистровые Машины Минского
  Мозаичные плоскости Пенроуза как более интересный вид пространства
  для клеточных автоматов

Большинство этих вещей довольно просты для понимания и неизвестны широкому
кругу программистов - значит будет интересно.
