#+TITLE: MailCrypt. Шифрование почты в Emacs-е

 Почта, это конечно хорошо, но кто же в двадцать первом веке посылает
 сообщения открытым текстом?! Поэтому поддержка шифрования в почте вещь
 совершенно необходимая. Вот и wanderlust можно настроить для работы с
 gnu-gpg. Базовыя статья по установке, на которую я опирался:
 <a href="http://box.matto.nl/wanderlustgpg.html">http://box.matto.nl/wanderlustgpg.html</a>

* Инсталляция

 Первым делом скачиваем библиотеку mailcrypt c <a href="http://sourceforge.net/projects/mailcrypt/files/mailcrypt/3.5.8/mailcrypt-3.5.8.tar.gz/download">http://sourceforge.net/projects/mailcrypt/files/mailcrypt/3.5.8/mailcrypt-3.5.8.tar.gz/download</a>

 Распаковываем ее в рабочую директорию, делаем

<source lang="bash">
./configure
make
sudo make install
</source>

 Прописываем в <code>~/.emacs.d/init.el</code>

<source lang="lisp">
;; MAILCRYPT
;; Commands:
;;   M-x mc-encrypt.
;;   M-x mc-wl-decrypt-message
;; http://box.matto.nl/wanderlustgpg.html
(load-library "mailcrypt") ; provides "mc-setversion"
(mc-setversion "gpg")    ; for PGP 2.6 (default); also "5.0" and "gpg"

(autoload 'mc-install-write-mode "mailcrypt" nil t)
(autoload 'mc-install-read-mode "mailcrypt" nil t)
(add-hook 'mail-mode-hook 'mc-install-write-mode)

(require 'mailcrypt)
(add-hook 'wl-summary-mode-hook 'mc-install-read-mode)
(add-hook 'wl-mail-setup-hook 'mc-install-write-mode)

(defun mc-wl-verify-signature ()
  (interactive)
  (save-window-excursion
    (wl-summary-jump-to-current-message)
    (mc-verify)))

(defun mc-wl-decrypt-message ()
  (interactive)
  (save-window-excursion
    (wl-summary-jump-to-current-message)
    (let ((inhibit-read-only t))
      (mc-decrypt))))

(eval-after-load "mailcrypt"
  '(setq mc-modes-alist
       (append
        (quote
         ((wl-draft-mode (encrypt . mc-encrypt-message)
            (sign . mc-sign-message))
          (wl-summary-mode (decrypt . mc-wl-decrypt-message)
            (verify . mc-wl-verify-signature))))
        mc-modes-alist)))
</source>

* Использование

 Теперь можно использовать команды <code>M-x mc-encrypt</code> и <code>M-x
 mc-wl-decrypt-message</code> внутри буфера сообщения, для шифрования и расшифровывания
 сообщений. Для тех, кто захочет послать мне шифровку прилагаю мои публичные ключи:

<source>
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.10 (GNU/Linux)

mQINBEyBOy4BEADaWAyD8dzRGHXc2isU79XyVy1Q/SmQUC8xFmlV3RzrEIQlj+gJ
JwoCAqbIiwNRbXVv++sxnlldmZZSvWx9qecrUiL2Paj45fJS0gRWRr7TvHue8Ayg
+73BvDaTbFTdv4kthpTAlsyAbdJwmAb6i69ZcS0/eYnlEYIcNkDKGwugJUtEJoUQ
JIcqKCh9+LxW2AvHf5QgwB0+woRcJUsiCX39QI6Ryr9sMtDn6ktQFQwxEpReUs1M
YEoTIlQZ1ZoDDkPKzhCvyYNlEyPgXBMpfW9yEeRF8eQh0Qho75e+inOnBUvgxy22
iwwAuYMm/LNDkmFebq2Yv51YrOHjhUn88wPyw/yrAEBgWxKYbUMqcmkXAxf8jtxd
RLzi/wJRC4SSyOXvf29dJJVIuO2/CCdCQak9HTXguhbZYdB8Xo7fzSFBEJXg5z4E
N8GFF4um69vqFPwU+QH0UYJQbxfZWsyu3oBXL4BGEeQLDgkyKh1KKTfAeC6xVdb9
lTKmcrjGiTAtwiiPsPdlfh7hllT7aVDFb5q1eS/i2XB+9FajUZRWn2KjDbf4NK+e
gkrJlkF8eivbofTwrbrpa5lcJpxCuQorBplLwogqY5HPedVgIYs2QNuHTylqvv+1
osWFf8OkBG126YWONZrrY4gvwYw7Ds4AoMO/m3spoMJK6ExZV5TQ8yeNMQARAQAB
tB9hdmVuZ2VyLWYgPGF2ZW5nZXItZkB5YW5kZXgucnU+iQI4BBMBAgAiBQJMgTsu
AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRDDJJA0rrTCU2RLEADVxekL
yBym6y8kndxwsndPfgXHPjDBWLBn/IJ6lAHvKW/Chzs6tfHMv9bLpR6yep718vTp
oYFCmCsQZcOqP9JeI7YF2ldUlGwseBVLcvkPi/A83m5LupUYNe5oaU/vAFMjLCEW
qO9OO3qjCyfSsyHtngJlwMSKi4otW9Ezff8WmT94lOD9xpnBIFaAeZbN6nt21v4D
cFLCmc69iWjhSAs8PggeJqopKJf0r/1ABZlXrflUXGLJGOwhOV2yHVLfHqo5c9Oc
o9sGxjlg/GAtRIyLUN+7xRV9wJJriuFaRPtxggIKYEUEa1p1RjQ6Cf+01070x9mR
yYaDWCbC8TU9ZqAdh8y3aSWgQIohWL7/+mowdrqPDvRGUMVE3qCCl9i4rZ6yZmiL
d687mklQniH0nIadMZ9L02hBkWXZoXyipt78izq/kdHDX0VAS80JcB47u6qIcK/a
cAOx5Z1JZmgyp2KZ/YJz2UU0su4herHraTpSQ5xxDwKbNNkcpbWevxRT4OUg17eQ
2cMKu280MZ24taS+wSaJaLHT3DqpuKEKaXlunbyp/2dVaf568S7f1iXwHzkp0fUO
dJCZWGy0Djb1vIsGhUlq+r+QDeUIgI4Y9VmL8yl5DcYwrJRimosdB6FfoEyyDm5P
r0KBye4BkbMS4t7+rc/c0rPTgAi9lby/QLL527kCDQRMgTsuARAAxYkhS51a1IgW
+k7Lre4veLZlKMGRqx+EWuk/fjLIKboc1IXt965iUJkIIf3WreZ3AYNyhX+WerhT
QOE9QwVq4yHEbuiagbVVQiTM2G2RMtTdyQLPh3p4rCNE7tjpqtNxLGQMHJyL8i8J
GCn01CniPDhBQz84W1YOSu6mtF2/8XSxymiJ/PBC9FnUfm2uK2O3OXdB6S4wP0hB
GISQxcmgzTOnZMRh25LmbTSFXcQMB+DBsBpfwWX5TsBf9R+X7zEw+GUoM9Gc4XeM
yfhbTYHp0Ci8yDINZLdUUNs1j31L1sw+1LE3mxE36ql9WeaTP+5ZCV+NPPXXmtJn
150Uj5PoKlGN/AH/0o4YNoETvIZI2JrhhVfxlWvTXTQwrBtGKbTSvEV+DliBQc66
HE5Xz2nKYhOKA7OdGWF3buyi80zkc2EBAzmX9E1M+rSmZ4UL0VCX+C8s+K3q/VE0
t2oxzuRNlLJrdJ+FvYdJB4Soo8B7ZK2EInle26YyXoex8d1lbN2m+uKgN8adqYbi
pmuuhQA/Q3KULIs2c5K85K8y7yRkWTaq1HIMVA+c5IdTY5bRg0hsU/lsqg+EbCaQ
Cub37LrOJx67uJkw1diHf5qRs34DXVvZvi7739VuZ/EN8g/lDjJ50wC156l7CCWn
U/Cx42wSLWYvjfK+AAMNGYAdvTzH5+cAEQEAAYkCHwQYAQIACQUCTIE7LgIbDAAK
CRDDJJA0rrTCU1XZEACMLgaCb11Zm4ns/0q18h/RvibnLqC8Zlt5I23l2AyrG8/a
Iq3NnYxiRm6nAwCwVCpO9KuvtFN0e8y4RZLpkMMMYFqk9nlW1bn9LyPQzAxHaacn
WelPJYrf/csgXUEIU71p+OYmSip7q1a/LXrQvqHaGQiyivaFKhHBcRLbxtWV5yzF
4LxngQF9Z0YTmAdI6WjrAgTqhe7m3PxJAhDvWKLKQ9zqddpO8qeA+HWRVECshNOl
cgNogXyYgqnS6z1F7Z5e1D5cbav4bU9/JD8JjRzOKlQ2v817mIDZsz6ZiH0P2Prh
0knhUUOx8yqF51rPlXeKuckNMrvDMr4kZSsI6UCBZrtzKkvoeBm8ms5VOf3GdpZw
9gIFh8fysc0Fd28/jtQGv9F017tAhHOY6s5a3+LPSXyyQG+0WZ8SxMqIATthb3JM
fik21UFaOKLEabv7jFI1XjSRVtoYMcMV1G7Xn6wUcJCnhOWaoanKZXPBkkwHkv4S
LByG0k90mOg0AbfNeDklTl6UdRnDEk6Nbb4nWYqzuakcur//cm+dv5+0GOXQb0nM
m2uUp8Fc/+dQbrqsqPwA21sKzKn+Kw3pjDYWyvMlN3eWl4qI/3PVpJQB5rqlk42s
6p43X0scXpSYI0TBLl5cKQHHZh0zDTFtpd+K7jARFht0P/8t+PJbuCrN6pcfUw==
=usiB
-----END PGP PUBLIC KEY BLOCK-----

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.10 (GNU/Linux)

mQINBEyBOeMBEAC78YrkuarCJgmFd12/Q1P086f8YMw9zCQLFm/H/AWlhwInetAR
Gg0UEd8VlLpvp5xOa/+1xM2bGHs7kQwDT/zVuZy28or2c+XsN8fKgEgIsyN+q5pC
5+Gui0izkWKHj+rcpKNSu2FhVMG0116KE+fvuy8rlGKT4mneIpLIxb8dqUB6mRNY
C2LMzqOsdodMivcPwujxYk9EZ18I8Rd9fLixPHjekf33vQE26dKkOhf6veFWBR8z
ywV/hOgLSGpPz3UE3ixmUr6XKddk41lkT9Eat6Z4EdLZDU2C2q9JpbdJvZtyXwBk
WcwAJSuvEpE2nB3VHhKtAXSoIbnQgnr8SALUaIqth1x2kBqCPqpOGjBNG0dHMuV9
jlprrqTXcYZivyDjCsOLEBYc7W1Q6AGykt4VqGMYO2lBVSRca8B8dGX5YnZ/omGb
N7foSH4Cyw85O9CAYNtWU1kTJSYUHRH8zlKgUIdXC+7vjbZdjxKxdXX1eu0Q9Bvd
CTi02PfZkjQTeyo/cIe+2IceuZ4aeYaMlLE2JJTTe+QGxphxsYdvbxQX+4+SsZY9
UOuZQCz3oZ1Aoa9ip3OzToJJtu9J3kEPo/7Kvjb/QzVRLSE/2Btm2x7kGgAFsfsW
BoN+Vm6UDBx0rVcvacIas9LgUBSexDDiKtz+nhlX4/8jX5iVDLxlQo8wqwARAQAB
tCByaWdpZHVzIDxpLmFtLnJpZ2lkdXNAZ21haWwuY29tPokCOAQTAQIAIgUCTIE5
4wIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQbVdwJ9XvXPakog//cK/j
zjzBwpiFv5d/Lo74CRcFfc8R0r+bXuZ16bPC21H40JMMMYQL1Bls9JA6/qQCdNfF
RL1djo8CWQEnD4oOlL8C27ZM5ykOjtGcLHB86BdJxE1tvSwi1ApIKI5rbSnyvG/L
NH8o2YMuhG8kzibRPCcF4xoJh4D9olT8gtgF7InhUnNwED/JPSVuWeWBszE8h3HQ
DrADy2Pt0EUnTjlr5etjYE+TtVydvY3m1KBrFZ+AnpTtv+E33setpd7Ks/yctJ65
j2xu/AukwDhmn314s2EV8AQ6xZNj/1TeuMNb2SGokooknCgtbramckBMdKOCenmf
HCNVnp238feUzOQs+86F48HhXsTlqcSuGk+7wrepozY+6ZMSyUqe59Wi9+l8OhZN
x92kx6B80Sb9Fb3det6Pi4v21D2XQRntLN7CoCNZ9e4d1uXkApd8jo+axLHmF4By
7fb+315y5DSIG53jqEoNRqxPzC5eXTtFYJtqOMmOCFRAipINOWdJIe67F7quCGrh
+VzJY3jhy5UbhAts21sLN6zU4z7eqhj80YjT+GE0V5Mab83w4y06XyKflL3IN2Rf
ZldWcjIj+DVIE9+8Nd2a+7+ArsUkXsvFYoLFqMpr3liPWLB+m0ycgIwIX35YN0tt
xXcocf3iYGTW7tQMgW7gnzQJdppwAHVoIpOFpDG5Ag0ETIE54wEQAJaWRno5aoLV
KL272L0I6dlDxU+HSLx1PvxtuV0TeydXKoKlzJ9jkcVOvx2lgXKruskFtMe2Vy8z
b2SRgSeKMpwuwTpqJ03lG/MZXQ81urBXnk+gFzjSIktDmvmrkakfb/RJQ/OkLpbB
7mb3poF+fgpxjUSwDYGSyUxP64I+t2Gsde/UILQ38XGuWySpkXMa6sMsWGysIdkN
Ndi+loqO+TtUfvZm7rBI+jChX8fOAsQ+10378G8AexnZfPGp8g+DfL2fUxDaC5G6
6283HDH+GFYe+8VX7Z6FbtukHaDfIu4/tQLXRQaRYFVf+26UYx+GoMU2qz2jZIId
KZ7h+qazV1N0nrEQT1OkoNyoh20RdDO+pRwC7VS3OOyfJbuhzgbG5k+uDvpVQtoG
bpeFOKqYKc7tRg510xZEokhGx8dBRAI3TJpboJSqdxCyM/ScGDNZ+ywT9FSI6hc+
SUaM/BmyDDXhAtPPy6psVbJBXVR8QLeZZch9iO1SNL1WohJ7np3cwZMyyudJY/5Z
MzLtLJjIPC9vjDxshMMA55109JGieCA/ofs/beiuxShlIw95IGoGVEzMe0dtAXyL
hbgHzh6PjLaZqDMUpQhxx3mb8Sob+2jR4FSFu8sZqJKwWzigabXoN/eWEcuJQZlZ
lQx3whGVuC58q+k6yNigG9zOLUnfY3ffABEBAAGJAh8EGAECAAkFAkyBOeMCGwwA
CgkQbVdwJ9XvXPY2+g/9GZbncRzaUYBrcu+yBNMWta/CoYkbJAtkpwPDMvGttFxA
6OhPA6nE3sMwHHgruC0xrK44dvfTzA+afGCuAxEKoefx3UfAOj0ES3p1HoeumfDO
tjQ7BEUfDLMd/eTkJ5NPf0o5mKYyEO6840rqN1Hnf6G/OKGNdY+sAe71+5uJBBou
P/U8oBUbf2ckWEDEcMVWdgb+csCUiahZYYoh4gvCJw9eHxTHXG6BoiwhOccozHFU
gs19cqqqqnWxeL+2/EZYS6gEpgXK6VaYrOT8qBkh26uuL76pPM/fpU1KfvkpukRw
oHfjrLZIutGziqE94WQhwp1+vvsan/2XPbDjNa1VNUVD0z43Lm2VhwNLhWBmdner
14rtDySP4Ii9+s5j+LPXI6LpMQROsiz6RdKmJoxPzkyeHN6grzbaUOffpOMwm7Gn
JUlZVm+qzGbkletOqZpEfRQGbc9T2uZFE2FwnFuZjtfN7dkaMzfCxciOIB1qeEZB
dqExVmKTtOoQQ8iC8eLLjAG43SGkdzjJ49qxwJPd1zI5PjO775PlxiZkKvvbxXau
UE+5/wxgTb2gx+VaE7FDcouTwUmhBXHPrqthAIjcYn4dtro/EhmUxkbkl7Zc1oSr
XEQMJ/2pyvGbb9dkWFj6z7L+tJXDHBAf+ag/3JYtbAY+EerVVj2lc0WNQgTC/DU=
=2FJ6
-----END PGP PUBLIC KEY BLOCK-----
</source>

И, на всякий пожарный, инструкция по использованию шифрования в gpg на
русском: <a href="https://nordrus.org/security/gnupg_manual_linux_w_sendkey.pdf">https://nordrus.org/security/gnupg_manual_linux_w_sendkey.pdf</a>
