#+TITLE: Полезное расширение — uniquify

Итак, настало время подключить к Емаксу нашу первую библитеку
расширения. В качестве простого примера я выбрал uniquify - маленькую
библитечку, распространяемую вместе с Емаксом (то есть качать ничего
не надо), которая улучшает способ работы Емакса с буферами, которые
отображают файлы с одинаковыми именами. Более подробную информацию о
ней можно посмотреть на emacswiki.org: http://emacswiki.org/emacs/uniquify

По умолчанию, Емакс отображает (в списке буферов) такие буферы как
filename, filename<2>, filename<3> и так далее. А uniquify отображает
в имени буфера кусок различающегося пути: filename/folger1,
filename/folger2 etc, что несомненно удобнее.

Итак чтобы подключить uniquify вы должны вставить в свой
~/.emacs.d/init.el следующий код:

<source lang="lisp">
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;; EXTENSIONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; http://emacswiki.org/emacs/uniquify
(require 'uniquify)
;; (setq uniquify-buffer-name-style t)
(setq uniquify-buffer-name-style 'reverse)
(setq uniquify-separator "/")
(setq uniquify-after-kill-buffer-p t)
(setq uniquify-ignore-buffers-re "^\\*")
(setq post-forward-angle-brackets 'post-forward-angle-brackets)
</source>


Это было несложно, не так ли?
