#+TITLE: Применение Dropbox в production

 Обнаружил на новом боевом серваке проблему, связанныую vsftpd - он не понимает ftp-команды
 list, предпочитая ей nlist. Моя файлзилла так работать не хочет, а патчить ее не хочу я. Вышел
 из положения довольно таки оригинальным способом - установил на серваке
 Dropbox-клиент. Дропбокс - это файлообменник-синхронизатор, с возможностью шарить папки,
 бесплатным 2ГБ пространством (путем инвайтов увеличивается до 8ГБ), настолько простой в
 использовании, что его можно рекомендовать в качестве рабочего инструмента для общения с
 дизайнерами, верстальщиками и менеджерами, которые с непониманием смотрят на Git и пугаются
 слова "бранчевание".

 Дропбокс работает под виндами, маком и линуксом, и даже под серверными линуксами, что позволяет
 использовать его для развертывания конфигов, картинок сайта и подобного барахла, типа
 css. Можно развертывать и пхп-код, если кто интересуется :) Чтобы развертывать лисп-код - нужно
 его подхватывать на лету как пхп, что выглядит ненужными телодвижениями, потому что у нас есть
 SLIME.

 Я создал два аккаунта - один свои и один серверный. На серверном создал папку для шаблонов и
 расшарил ее верстальщику. Потом еще одну для конфигов и прочего стаффа - и расшарил ее всем
 кого касаются конфиги. Еще одну можно расшарить для контент-менеждеров. Ну и одну - самую
 большую оставил для себя - храню в ней вкусные бэкапы на всякий случай. Получилось удобно.

 Так что если кому нужны инвайты - обращайтесь. Использование инвайтов увеличивает бесплатное
 пространство и тому кто инвайт посылает и тому кто принимает его.

 Еще одна полезная ссылка: <a
 href="http://wiki.dropbox.com/TipsAndTricks/TextBasedLinuxInstall">http://wiki.dropbox.com/TipsAndTricks/TextBasedLinuxInstall</a>
