/* Autogenerated with DRAKON Editor 1.27 */
#include "diagram.h"


static void SnakeGame(void);

static void lib_init(void);

static void render(void);







static void SnakeGame(void) {
    // item 19
    lib_init();
    /* item 20 */
    render();
    
    item_21 :
    input();
    /* item 24 */
    update();
    
    // item 22
    if (gameover) {
        /* item 23 */
        bye();
    } else {
        /* item 26 */
        render();
        /* item 25 */
        delay();
        goto item_21;
    }
    
}

static void lib_init(void) {
    // item 60
    lib_init();
    /* item 61 */
    create_window();
    /* item 62 */
    load_textures();
    /* item 63 */
    clear_tails();
    /* item 65 */
    init_snake();
    /* item 64 */
    init_fruit();
    /* item 66 */
    set_direction();
    
}

static void render(void) {
    // item 81
    if (snake_len > 1) {
        /* item 84 */
        draw_body();
    } else {
    }
    
    // item 85
    if (eaten) {
        /* item 88 */
        draw_fruit();
    } else {
        /* item 89 */
        clear_tail();
    }
    
    // item 90
    draw_head();
    
}



