/* Autogenerated with DRAKON Editor 1.27 */
#ifndef DIAGRAM_H99727
#define DIAGRAM_H99727








public class SnakeGame {
private:
    // non-copyable
    (const & other) {}
    void operator=(const & other) {}
};

#endif

