
* Структура и интерпретация компьютерных программ (SICP)

  Материал этой книги был основой вводного курса по информатике в MIT
  начиная с 1980 года. К тому времени, как было выпущено первое
  издание, этот материал преподавался в течение четырех лет, и прошло
  еще двенадцать лет до появления второго издания.

  [[http://rigidus.ru/resources/sicp.pdf"][Структура и интерпретация компьютерных программ. Абельсон, Сассман (перевод: Ю. Бронников)]]

* Типы в языках программирования (TAPL)

  Книга о теории типов. Рассматриваются вопросы проверки и
  автоматического вывода типов в языках программирования со
  статической типизацией. Для каждой темы сначала дается теория, а
  затем приводится реализация на OCaml.

  TAPL — это, бесспорно, настоящий кладезь знаний для разработчиков
  языков программирования со статической типизацией.

  [[http://rigidus.ru/resources/tapl.pdf"][Типы в языках программирования. Бенджамин Пирс]]



* Как проектируются IP-блоки и системы на кристалле

  Юрий Панчул прочитал эту лекцию в Алма-Ате и я подготовил небольшой
  конспект. Осталось немного довести его до ума и я выложу его на
  сайт, а пока доступно [[https://www.youtube.com/watch?v=sPaMiEunT_M"][видео]], [[http://www.silicon-russia.com/public_materials/2016_09_01_kazakhstan/day_1_industry/03_slides/03_extra_eda_flow_2015_10_25.pdf"][слайды]] и его [[https://habrahabr.ru/post/309570/"][отчетный пост]] на хабре.
