#+STARTUP: showall indent hidestars

Das ist SmartContract prototype tasks

* Мультисиг

общеизвестно

* Atomic swap

Например, у Алисы есть 200 лайткоинов, но ей хотелось бы иметь 1 биткоин, а у Боба есть
1 биткоин, но ему бы хотелось получить 200 лайткоинов. Алиса и Боб соглашаются на
обмен, но они не доверяют друг другу, поэтому ни один не хочет первым отправлять
монеты.

Алиса и Боб могут воспользоваться атомным обменом. В этом случае безопасность
обеспечивается специальным алгоритмом под названием контракт с временем,
заблокированным хэшем, который использует потенциал мультисиг адресов и блокирования
времени. Весь функционал обеспечивает внутренний язык программирования биткоина и
большинства альткоинов, включая Litecoin и Decred.

Алиса и Боб проводят транзакции в обоих блокчейнах: одну в биткоин, одну в
лайткоин. Транзакция в блокчейне биткоина передает 1 BTC Алисе, но она может получить
монету только предоставив секретный код. Транзакция в блокчейне Litecoin передает 200
LTC Бобу, но он получит лайткоины только когда он предоставит секретный код.

Когда Алиса получает монеты, она дает свой секретный код и только с ним Боб может
получить свои лайткоины. Несмотря на то, что транзакции проходят на разных блокчейнах,
они связаны. Бобу только нужно следить за распределенным реестром, чтобы понять, когда
принимать токены.

* Схемы продаж и доставок товаров.

Типичный контракт гарантированной поставки (с арбитром и без)

* Аукционы

Во всех типах аукциона нам интересно минимизация возможности подставных ставок со
стороны продавца.

Стратегии с т.з. теории игр (от Сергея Николенко) тут:
https://logic.pdmi.ras.ru/~sergey/oldsite/teaching/auctions/02-exampleandrevelation.pdf

** Английский аукцион (аукцион повышающейся цены)

тип аукциона, основывающийся на установлении минимальной цены в качестве отправной,
базисной для дальнейших торгов, в процессе которых запрашиваемая цена пошагово
увеличивается и ставки известны всем участникам. Итоговая цена формируется в ходе торга
из последней максимальной цены, предложенной одним из покупателей который и становится
победителем.

Вариант: с ограничением по времени (пока горит свеча)

** Голандский аукцион (аукцион понижающийся цены)

аукцион, в ходе которого вначале объявляется самая высокая цена на продаваемый товар, а
затем ставки снижаются до той, на которую согласится первый покупатель, которому и
продается товар. Получил своё название в силу широкого распространения в этой
стране. Характерная особенность в том, что это оптовый аукцион, на котором продавец
может выставлять много единиц товара одновременно.

** Закрытый аукцион первой цены

Аукцион первой цены (first-price sealed-bid) является закрытым, поэтому участники
направляют свои ставки в конвертах и победителем является аукционер, предложивший самую
высокую.

За лот он платит "первую цену" - величину своей ставки.

** Закрытый аукцион второй цены (аукцион Викри)

Аукцион второй цены (second-price sealed-bid auction) – аукцион, в котором победителем
считается участник, предложивший наивысшую ставку (bid), но заплатить он должен вторую
максимальную, то есть цену ближайшего конкурента.

Выгоду от проведения аукционов такого типа имеют и участники и проводящая сторона:
участники определяют настоящую ценность лота для себя и называют именно ее, без
искусственного завышения. Организаторы оказываются в плюсе, так как участники в итоге
делают более высокие ставки, чем при аукционе первой цены. Данная модель позволяет
проводить аукционы очень быстро

** Аукцион однородной цены (the uniform-price auction)

В случае множественных идентичных (или делимых) товаров, реализуемых в рамках одного
аукциона, очевидным обобщением является продажа товара всем участникам, выигравшим
аукцион, по наибольшей цене неудовлетворенных предложений. Является обобщением
закрытого аукциона второй цены

** Аукцион Викри-Кларка-Гровса (VCG auction)

Обобщение аукциона Викри на случай продажи нескольких товаров, сохраняющее стимулы к
правдивому назначению ставок, известно как механизм Викри-Кларка-Гровса
(Vickrey-Clarke-Groves, VCG). Идея VCG-аукциона состоит в том, что каждый участник
аукциона платит цену исходя из того, как его участие воздействует на всех остальных
участников. А именно, каждый игрок платит по итогам аукциона сумму, равную
недополученной ценности товаров другими игроками из-за того, что в аукционе участвует
этот игрок.

Например, предположим, что мы хотим продать через аукцион два яблока, имея трёх
участников.

- Участник A желает одно яблоко и делает ставку $5.
- Участник B также хочет одно яблоко и готов заплатить $2.
- Участник C претендует на два яблока и намерен заплатить $6 за оба, но не желает
  приобретать одно яблоко без другого.

Во-первых, мы определяем победителей путём максимизации ставок: яблоки отходят к
участникам A и B (поскольку проиграв одно яблоко участнику A, С не претендует на
второе).

Во-вторых, чтобы определить платежи, мы рассматриваем что произойдет, если бы
победитель не участвовал в аукционе.

- Платеж победителя A: B получает яблоко, сделав ставку $2. Если бы участника A не
  было, C выиграл бы оба яблока и заплатил бы за них $6. Так что A платит разницу между
  ценой C за оба яблока и ценой B за одно из них: $6-$2 = $4.

- Платеж победителя B: A получает яблоко, сделав ставку $5, а C не получает ничего. Не
  будь B, C получил бы оба яблока за $6 (поскольку $6 за два яблока превышает ставку A
  $5 в отсутствие других участников). Поэтому B платит разницу $6-$5 = $1.

** Закрытый аукцион максимальной ставки с поглощением других ставок (All-pay auction)

Все участники делают ставки. Выигрывает тот, кто заплатил больше всех, но все деньги
собраны, и, соответственно, есть участники, которые ничего не выиграли, но заплатили
свои собственные ставки.

Пример использования: лоббирование

* Краудфаундинг

Практика финансирования проекта путем сбора небольших объемов денежных средств с
большого количества участников.

Компания ограничена по времени, имеет цели (soft-cup, hard-cup), участники получают
заранее определенное вознаграждение и несут риски в случае провала компании.

Вознаграждением может быть материальный результат продукта.

** Краудлендинг

Проект кредитуется бэкерами, рассчитывающими на возврат долга, возможно с процентами

** Краудинвестинг

Вознаграждение - доля в предприятии, право голоса и право получения дивидентов.

* Бонусные системы

Покупатель получает дополнительную награду за совершенные ранее действия (покупки), в
зависимости от ценности этих действий для продавца. Бонусы могут быть конвертируемы в
иные ценности.

* Кэшбэк

Отсроченная скидка, возвращаемая по истечении времени.

Схема кешбэка отличается от традиционных дисконтных схем и скидок и состоит в
следующем:

- Клиент оплачивает продавцу розничную цену (при этом могут учитываться любые обычные
  скидки и акции, объявленные продавцом);
- Возврат части стоимости покупки (бонус) клиент получает от другого лица — не от
  продавца, а от аффилиата, обеспечивающего продавцу приток покупателей;
- Источник кешбэка — комиссионные, выплачиваемые продавцом аффилиату за каждого
  покупателя. Указанными комиссионными владельцы кешбэк-сайтов делятся с
  покупателями, стимулируя их приобретать товары и услуги на своём портале.

* Билинг и тарифные системы
** Абонентская плата

Оплата за время использования услуги, вносится перед началом ее предоставления.

** Оплата за трату расходуемого ресурса

Пример: плата за интернет-трафик.

** Оплата за занятие ресурса на время

Пример: тарифы телефонных операторов.

** Плата за подключение
** Плата за простой (неиспользование)
** Тарифные условия
** Условия скидок
* Биржи
** обмен валютных пар

В смарте мы должны явно прописать процедуру обмена, привязанную или не привязанную к
текущему курсу валюты.

** Фьючерсы и опционы

Контракт с двумя изменяемыми полями - ценой и сроком поставки, воспринимаемый как
товар.
- Поставочный фьючерс: поставка осуществляется по цене на последний день торгов
- Безпоставочный: рассчеты производятся в сумме разности между ценой контракта и ценой
  на дату исполнения.

* Тайм-доллар

Подвид экономики, основанной на временном факторе (ЭВФ). Основной целью ЭВФ является
замена рентной системы установленными за выполненные работы нормативными платежами,
которые зависят от времени (являются математическими функциями с параметром "время" в
качестве аргумента). По принципам ЭВФ, капитал не может увеличиваться со временем без
осуществления труда, длительность которого будет соответствовать его увеличению.

Банк времени фиксирует для своих участников сколько времени потрачено участником на
оказание услуг другим участникам. Единица расчета обеспечивает обмен услугами и
взаимное кредитование. Время всех участников оценивается одинаково, вне зависимости от
содержания выполненной работы, от образования, навыков и умений.

Банк времени функционирует по правилам, которые предусмотрены Методическими рекомендациями:
- Накопленный за месяц излишек времени работник передает в Банк времени, причём 85 %
  этого времени заносится на лицевой счёт работника, а 15 % передается в фонд общего
  пользования (фонд начальника).
- Накопленное время в Банке подлежит использованию в течение года.
- Руководство Банком осуществляется Правлением в количестве двух человек (из
  представителя администрации и профсоюза). Правление избирается сроком на один год на
  профсоюзном собрании подразделения.
- Выдача времени из Банка производится решением Правления по заявлению
  работника. Полученное время может быть использовано в течение календарного месяца и
  неиспользованная часть возвращается в банк. Допускается по согласованию с начальником
  взятие отгула за счёт времени из банка.
- Фонд общего времени может быть использован для оказания безвозмездной помощи
  отдельным работникам или для проведения общественных мероприятий.  и использовании
  рабочего времени из Банка за работником сохраняется установленная заработная плата за
  месяц. В карте учета отработанного времени делается запись о получении из Банка или
  отчисления в Банк рабочего времени.

https://chronobank.io/ - то же на блокчейне, токены номинированы в часах труда и
привязаны к средней почасовой ставке страны

* Свободные деньги (Freigeld) Гезелля

Денежная единица, требующая платы за хранение (демередж), которая вносится тем, кто
владеет ей в конце оговоренного срока. Цель демерджа - ускорение денежного обращения.

Гезелль считал, что владение деньгами для держателя приводит к ничтожным издержкам
хранения, в то время как хранение товарных запасов или содержание производственных
мощностей связано со значительными издержками.

* Хэджирование

Хеджирование путём открытия противоположных позиций на рынке реального товара и
фьючерсном рынке. Например, заключается контракт на поставку пшеницы. Но урожай ещё не
вырос, есть риск сорвать контракт. Для минимизации рисков покупается опцион на поставку
аналогичной партии пшеницы по аналогичной цене. В случае если рыночная цена будет ниже
ожидаемой прибыль от опциона покроет убытки от поставки. И наоборот, в случае если цена
на реальном рынке будет выше, прибыль от поставки покроет убытки опциона.

* Страхование

Страхователи формируют фонд, перечисляя в него взносы. В случае, если оракул
подтверждает наступление страхового случая, смарт-контракт перечисляет деньги из фонда
страховщику.

В смарт-контракте должны быть прописаны страховые условия и могут быть прописаны
комиссии и инвестиционная стратегия.

* Кредитные кооперативы

Аналогично страхованию, но для целей кредитования.

* Сетевой маркетинг (MLM)

Создание сети независимых дистрибьюторов, имеющих право на привлечение партнеров на
таких же правах. Доход агента зависит от собственных продаж и от продаж привлеченных им
агентов.

Условия:
- Стоимость входа
- Минимальный объем реализации за период
- Стоимость возврата Возврат непроданной продукции (% от цены покупки).

* Реферальные системы

Для распространения бонусов, инвайтов, скидок. Так же как MLM, но более
интернет-ориентировано: привлеченный клиент должен выполнить набор действий, чтобы тому,
кто его пригласил, было защитано привлечение клиента.

* Потребительские кооперативы

Позволяет удешевить товар, путем уменьшения закупочной цены и транзакционных издержек.

Условия:
- паевые взносы
- ограниченное число паёв у каждого кооператора
- все кооператоры равноправны и каждый имеет один голос

* Аренда вместо владения, Sharing economy

Каршеринг, велошеринг, аренда места в гараже или паркинге, airbnb и.т.п.

Условия:
- Плата за вход
- Абонентская плата
- Плата за время использования ресурса

Аренда парковочных мест и каршеринг хорошо можно автоматизированно сочетать, а
p2p-каршеринг до сих пор нереализован. Hack-sharing еще

* Совместное владение и управление

Также как и в остальных сценарях, нам нужен ответ, кто в данный момент владеет ресурсом
и процедура передачи владения.

Управление сводится к разграничению доступа и голосованию

* Голосование

Формируем структуру =voter=:
- Вес голосующего
- Кому делегирует, если делегирует
- Опционально: разрешенные операции (делегирование)
- Сделанный выбор

Формируем предложение (предложения):
- описание
- результаты

Определяем создателя (обычно в конструкторе) и его операции.

Определяем голосущих: ключ-значения, где ключи указывают на аккаунты, а значения
представляют собой структуру =voter=

Операции:
- Отдать голос (предложение, опция)
- Делегировать голос
- Получить результаты

* Разраничение доступа, роли и права

На стадии создания необходимо связать аккаунты с разрешенными (запрещенными) операциями
для них, предусмотреть процедуры повышения привелегий и.т.п

* Сложная логика подтверждения решения

не просто "не менее N подписавших" а например "не менее и при наличии хотябы одно из
главных" итд.

* Системы отзыва ключей.

Требует ведения реестра скомпроментированных ключей

* Шедулер

Требует вызова контракта по расписанию, например: внешним централизованным сервисом,
публикующим транзакцию.

Децентрализованное решение для этого - смарт-контракт - scheduler, позволяющий
зарегистрировать вызов нужного смарт-контракта на определенное время. Тогда любой
другой пользователь шедулера может вызвать запланированный контракт (и получить за этот
вызов вознаграждение, которое полностью покроет газ, потраченный на вызов). Шедулер
позволяет вызывать себя любому пользователю, если вызывающих будет больше, чем можно
запустить контрактов, то вознаграждение получит первый вызывающий, который успешно
вызвал контракт.

В сторадже шедулера хранится запланированные контракты. Сам шедулер обеспечивает
требования:
- вызов произойдет не раньше запланированного времени
- порядок вызовов не будет нарушен

Получение первого в очереди на вызов контракта должно производиться за постоянное время
(не зависящее от числа контрактов зарегистрированных в системе) и иметь минимальную
сложность.

Структура данных в очереди ожидающих выполнения контрактов:
- адрес запускаемого контракта (20 байт)
- время запуска (4 байта timestamp)
- Gas (4 байта - все равно ограничено сверху большинством клиентов)
- Gas price (4 байта)
Все можно уместить в 32 байта.

Структура хранения: значение записи (32 байта) рассматривается как ключ на следующее
значение, таким образом создается связный список упорядоченный в обратном
хронологическом порядке. Одинаковые по времени записи упорядочены в порядке добавления.

Для поддержания списка в сортированном порядке, записи необходимо вставлять согласно
дате. Для ускорения поиска места вставки нового значения нужен индекс на базе
дерева. При таком подходе поиск элементов по дереву дает константное значение
сложности O(1), не зависящей от числа элементов.

Мотивация:

Любой пользователь сети, имеющий адрес и достаточное количество средств для
произведения вызова может приумножить свои средства, вызывая шедулер. Шедулер переведет
вызывающему вознаграждение, которое было зарегистрировано при регистрации контракта.

Момент, когда следует делать вызов можно легко определить при помощи метода который
возвращает актуальное состояние очереди: время ближайшего вызова, минимальный
газ, сумму вознаграждения по каждому контракту и другие значения.

Регистрация:

Для регистрации вызова контракта на определенное время необходимо вызвать метод
со следующими параметрами:

- Address — адрес контракта, которой необходимо вызвать.
- Timestamp — момент времени в формате unix timestamp в который вызов должен быть
  произведен. Важно понимать, что Joule гарантирует только то, что вызов не будет
  произведен ранее данного момента.
- GasLimit — максимальное значение газа которое будет предоставлено на вызов. Лучше
  указать значение с запасом, чтоб не возникло ситуации, что вызов контракта завершится
  ошибкой из-за нехватки газа.
- GasPrice — предполагаемая стоимость газа для вызова контракта.

В транзакцию вместе с вызовом register необходимо передать сумму в эфирах для
вознаграждения за вызов. В случае, если будет передана избыточная сумма — остаток
будет возвращен вызывающей стороне.

Если преждевременные вызовы могут нарушить логику работы контракта или создать
уязвимость, то следует добавить проверку, что вызов был именно от шедулера. Если
контракт уже в сети, и нет возможности добавить в него метод check, то можно
воспользоваться контрактом-посредником, реализующим нужный метод и вызывающий целевой
контракт. Тогда при регистрации в шедулере следует указать адрес контракта-посредника.

См. также: https://github.com/MyWishPlatform/joule, https://habr.com/post/348284/,
https://github.com/ethereum-alarm-clock/ethereum-alarm-clock/,
https://ethereum-alarm-clock.readthedocs.io/en/latest/


Мы также можем иметь шедулер в базовых контрактах сети, правда тогда придется
предусмотреть вознаграждение или иной механизм чтобы владелец ноды его не отключил.

* Векселя

Долговая расписка, инструмент рассчета посредством кредита. Используется для
превращения одно обязательство в другое.

Покупатель в оплату за товар выпускает вексель (переводной вексель, тратту), поставщик
(индоссант - текущий владелец) получает его и продает (индоссату - новому текущему
владельцу) на вторичном рынке, доцимилянт, купивший вексель, гасит его у
покупателя. Итальянцы...

Проблемы начинаются когда покупатель отказывается платить. Вокруг этого есть сроки
погашения, проценты и прочие условия.

* Аккредитив

Участвуют:
- Продавец
- Покупатель
- Банк

Сценарий:
- Заключение контракта между продавцом и покупателем
- Покупатель запрашивает у Банка оформление аккредитива
- Покупатель заносит на счет аккредитива деньги в полном объеме сделки. Банк блокирует
  деньги, покупатель и продавец не могут ими воспользоваться.
- Продавец узнает, что деньги на счету аккредитива есть, и после одобрения банка он их
  получит.
- Продавец передает товар покупателю.
- Банк проверяет это и если все в порядке - переводит деньги на счет продавца. Иначе,
  деньги возвращаются назад к покупателю.

* Депозитарный клиринг.

Клиринговая компания (клиринговое подразделение биржи), получив информацию о
проведенных операциях по купле-продаже ценных бумаг, производит вычисление позиций
участников. Засчитывает встречные требования и по незакрытым позициям дает поручения
расчетному депозитарию на поставку ценных бумаг покупателям и банку на перечисление
денежных средств продавцам. Эффективность клиринговой деятельности характеризуется
временем исполнения сделки.

* Факторинг

В операции факторинга обычно участвуют три лица: фактор (факторинговая компания или
банк) — покупатель требования, поставщик товара (кредитор) и покупатель товара
(дебитор). В некоторых случаях, здесь может быть и четвёртая сторона-посредник,
которая, например, предоставляет площадку или электронную платформу для совершения
факторинговых сделок.

Смысл в том, что факторинговая компания приобретает права на долги должника и
взыскивает с него их.

* Проектное финансирование

Способ привлечь долгосрочное финансирование крупных проектов, который основывается на
кредите под денежный поток, создаваемый непосредственно проектом.

Участники:
- Проектная компания.
- Инвестор
- Кредитор.

Средней суммой, которую может предоставить кредитор, является 80% общих капитальных
расходов. Получающая кредит проектная компания не имеет поручителя и залога, однако
доля заёмных средств выше, чем сумма, которую предоставляет кредитор.

Единственный источник погашения долгосрочных обязательств — денежные потоки,
генерируемые самим проектом, а в качестве обеспечения кредитных обязательств выступают
активы, формирующиеся в ходе его реализации.

* Депозит моновалютный и мультивалютный

Один или несколько счетов, позволяет уменьшить риски от волатильности. Может быть
пополняемым, расходуемым, иметь страхование вклада, дивиденты и прочие условия.

* Расчетный счет с овердрафтом

Овердрафт отличается от обычного кредита тем, что в погашение задолженности
направляются все суммы, поступающие на счёт клиента. Иногда предоставляется льготный
период пользования овердрафтом, в течение которого проценты за использование кредита не
начисляются. Это зависит от кредитной политики банка.

* Системы кредитов
** Кредит беззалоговый

очевидно

** Кредит залоговый

то же, но в случае плохого сценария залог переходит кредитору. В нашем случае залог
должен быть токеном, который определяет право владения.

** Кредитная линия

это предоставленное организации право использовать заемные средства банка в оговоренный
отрезок времени и в установленном объеме. Конкретные условия прописываются в
договоре. Данная услуга позволяет ликвидировать финансовые разрывы, не изымая капитала
из оборота.

** Кредит с поручительством

Поручитель несет обязательство за клиента, если тот не платежеспособен

** Банковская гарантия

 Поручительство банка-гаранта за выполнение денежных обязательств своего клиента; при
 неуплате клиентом в срок - это сделает банк.

* Escrow
* Биржа

Алиса регистрируется на бирже и выставляет order на покупку определенного количества
монет определенной криптовалюты. Боб, который уже зарегистрирован на этой бирже, видит
order и, если его устраивает цена, соглашается на него. Балансы аккаунтов на этой бирже
у Боба и Алисы изменяются. После этого, они могут вывести эти деньги на свои кошельки.

* Вестинг

Обычная схема наделения правами на акции (вестинг) охватывает четырехлетний период с
годовым порогом (клиффом). Это значит, что пока вашему участию в стартапе не исполнится
год, вы не получите долю в бизнесе. В первую годовщину вы получите 25% от оговоренной
доли, а затем будете ежемесячно получать остальное. То есть, если я — разработчик
стартапа, которому выделен пакет опционов в 4800 единиц, то через год я получу долю в
1200 единиц (но если до этого момента я уволюсь или буду уволен, то не получу
ничего). Затем, после преодоления клиффа, за каждый месяц работы в компании я буду
получать по 100 единиц (1/48 часть пакета опционов).

https://github.com/ontofractal/sagres_waves

* Smart Rewarding

https://forum.wavesplatform.com/t/smart-rewarding/1024

* Taxation

Ограничение, что при переводе надо отправить N% "государству".

* Lighting network
* Digital Identity
* TODO Лотерея
* TODO Системы маркирования принадлежности ресурсов, сметы, планы, целевое определение возможных трат.
* TODO Системы быстрого конвертирования и быстрого локального обмена.
* TODO Логистика?
* TODO Token Curated Registry

https://habr.com/company/mixbytes/blog/418711/

** Tickets

Sell/Purchase tickets, set ticket prices; NFT interchangeable with fungible tokens (easy to buy and sell)
Distribute/Redistribute tickets, Transfer (infinitely)
Set group discounts
Interoperable with partner systems
Anyone can verify the validity of a ticket simply by scanning the QR code that contains the ownership information
Non-transference without permission of the ticket owner
Track ticket’s resale history (logging all of the previous buyers on the blockchain) to ensure authenticity of the ticket
Enabling buyers to become resellers (for incentivizing ticket demand), invite their friends to participate in events
Event-creation fee
Set resell restrictions for fair pricing (deny increasing the price when resaling; set a minimum and maximum price caps)
Fee per each resale transaction (earn a share of resale revenue)
Employing biometric data (facial recognition or fingerprint scanning) to authorize users to purchase a given ticket
Anonymity + verification: encrypt and hash all user data to one-way verify that the customer who purchased the given ticket is indeed the person attempting to check in
Reward mechanism for referring new users
Encourage customers to buy early to gain access to special rewards
The metadata must be regulated by a consensus protocol so no new information can impact on existing assets, unless agreed upon by the consensus protocol
Track ticket sales and secondary transfers
Store Ticket ID, Event ID, Number of issued tickets
Store Price of ticket, Customer Digital Fingerprint, History of transferred digital fingerprints (in metadata)
Store the general Event information: e.g. event date, time and venue (in metadata)
Store ticket Status: an indicator showing whether the ticket is valid or not
Global pool of events
Randomized matching of ticket reselling
Token-curated registry to incentivise users to report fraudulent events or resellers
Event organiser can whitelist or blacklist chosen promoters and sales channels
Freeze period
Approved merchant events: the event’s tickets can only be sold or re-sold exclusively via whitelisted sellers
Set rules concerning how ticket ownership may be sold and resold
Use distance between the event and the user, starting date, category tags, and advertising fees to determine the hierarchy within the list of the events
Different ticket types on the same event
Ticket Auctions
SMS-auth
Add a photo/video to the ticket
See who else is on the concert
Redeem a ticket

** Games

Items can be bought and sold using fungible tokens
Can't reissue rare or popular collectibles making them worthless
Distinct visual appearance (phenotype) determined by its immutable genes (genotype)
Two items can breed to produce a new one that is the genetic combination of its parents.
A sire will have a recovery period before it can breed again
The second parent incubates the kitten, during which time it cannot engage in another pairing
Fee (per each transaction)
Users receive the revenue from item sales
New items are released periodically via the smart contract
Browse unique assets
Descending clock auction for non-fungible tokens: Buyers are able to choose their purchase price along that spectrum by purchasing when the price aligns with their perceived value. Buyers pay gas when they complete a purchase and sellers pay gas to initiate an auction
Auction for items selling
Place their pets available for sire by selecting a maximum opening bid for siring, a minimum closing bid, and timeframe for the auction
Random number generators are needed when issuing a new asset
interpret the pet's genes differently across multiple games allowing unique game experiences
Players can sell their item in the Exchange for a higher price than they purchased it for (only if other players want to buy them)
Players can upgrade their pets through gameplay/training; in-game events update the dynamic traits of the pet, keeping a record of achievements and upgrades
Prove the rarity and uniqueness of the item
The total supply of items emitted per day is limited, based on daily players activity
Play games with pets (some games/battles may require more than one pet)
Combining items according to a recipe, building complex items
Breaking items down into raw materials
Gold Pieces give players the ability to determine which new items, locations, and features are added to the game => true decentralization
Some items are only available for sale for around 48 hours
Equipping a character with select items that they already own
If the character dies, their equipment is gone
Random numbers via future block hash
List all items with certain attribute
See All Possible item Attributes
See All Top item Owners and their balances
Referral program: Invite Your Friends And Get 5% Bonus For Each Coin They Buy
Planets/locations
Users can mine resources/materials

** Ownership

* TODO Non fungible tokens (NFT), SmartTokens
* TODO Review

- SmartAccounts и торговля с них.
  Сейчас: stateless на основе проверки DataTransactions
  Потом - statefull
- SmartTokens = SmartAsset
- AtomicSwap
- IDE
- Workflow
- API: доступ к инфе о майнинге, время блока, высота...
- BMMN
- 5 фаз, которые проходит контракт?
- 15 типов транзакций
- Documentation as Product
