* О сайте

** Цель создания

   Этот сайт был изначально создан для сбора редких и интересных материалов о вычислительных
   моделях, парадигмах и языках программирования. Позже он также превратился в занимательное
   упражнение в реализации разнообразных программистких концепций.

** Исходный код

   Репозиторий с исходным кодом и историей коммитов доступен на
   [[https://github.com/rigidus/rigidus.ru]]

   Он открыт для любых дополнений и предложений в форме ~pull-requests~ и ~issue~

** Текущий статус

   Отдельные вещи здесь переделываются прямо на ходу и кое-что может не работать по двум
   причинам:
   - Во-первых, я изменяю их, чтобы привести в соответствие с моим текущим ощущением "как
     правильно"
   - Во-вторых, отдельный части изменяются независимо от моей воли по сложным, часто
     недостаточно оттестированным экспериментальным алгоритмам, которые было бы безответственно
     запускать где-то еще.

   Если вы заметили ошибку или еще что-то что вам не нравится - сообщите мне об этом. Вы можете
   воспользоваться для этого способами, изложенными в предыдущем подразделе.

* Обо мне

** Личная информация (Personal)

   Меня зовут Глухов Михаил, я также известен как Rigidus. Этот ник был выбран с целью
   упростить поиск в поисковых системах.

   Всю свою жизнь я занимаюсь программированием и исследованиями в связанных областях. Моя
   работа тоже имеет к этому самое прямое отношение.

   Я накопил значитетельный опыт за это время и готов делиться экспертизой.

** COMMENT Исследовательский опыт
** COMMENT Опыт работы
** COMMENT Награды
** COMMENT Публикации
** COMMENT Членства в ассоциациях/организациях
** COMMENT Образование
** COMMENT Дополнительные умения и навыки
** COMMENT Рекомендации
** COMMENT Работа, к которой я стремлюсь
** COMMENT Интересы
** COMMENT Личная характеристика
