* О сайте

** Цель создания

   Этот сайт был изначально создан для сбора редких и интересных материалов о вычислительных
   моделях, парадигмах и языках программирования. Позже он также превратился в занимательное
   упражнение в реализации разнообразных программистких концепций.

** Исходный код

   Репозиторий с исходным кодом и историей коммитов доступен на
   [[https://github.com/rigidus/rigidus.ru]]

   Он открыт для любых дополнений и предложений в форме ~pull-requests~ и ~issue~

** Текущий статус

   Отдельные вещи здесь переделываются прямо на ходу и кое-что может не работать по двум
   причинам:
   - Во-первых, я изменяю их, чтобы привести в соответствие с моим текущим ощущением "как
     правильно"
   - Во-вторых, отдельный части изменяются независимо от моей воли по сложным, часто
     недостаточно оттестированным экспериментальным алгоритмам, которые было бы безответственно
     запускать где-то еще.

   Если вы заметили ошибку или еще что-то что вам не нравится - сообщите мне об этом. Вы можете
   воспользоваться для этого способами, изложенными в предыдущем подразделе.

* Обо мне

** Личная информация

   Меня зовут Глухов Михаил, я также известен как Rigidus. Этот ник был выбран с целью
   упростить поиск в поисковых системах.

   Я родился в 1982 году в г. Ленинград, теперь - Санкт-Петербург.

   Мне можно в любой момент позвонить по телефону ~8(911)286-92-90~ или написать на
   ~i.am.rigidus at gmail dot com~

   Я занимаюсь программированием и исследованиями в связанных областях с 14 лет. Моя работа
   тоже имеет к этому самое прямое отношение.

   Я накопил значитетельный опыт за это время и готов делиться экспертизой.

** COMMENT Исследовательский опыт
** COMMENT Опыт работы

Следующим должен идти раздел Work experience или Professional experience, который также можно
назвать Work history или Professional career. Work experience и Work history содержат весь ваш
опыт работы, а Professional experience или Professional career включают в себя только то, что
непосредственно относится к вашей профессии. В последнем случае после Professional experience /
Professional career при необходимости следует раздел Additional work experience, в который
входит опыт работы, не относящийся к вашей профессиональной деятельности (например, если вы –
финансист, то additional work experience – это опыт работы няней, репетитором, официантом, и
т.д.). Когда вы описываете два своих последних места работы, включайте описание Key
responsibilities (основные обязанности), которые у вас были / есть. Работодателям интересно
знать, за что именно вы отвечали на занимаемых должностях. Кроме того, в описании последнего
места работы не помешали бы и Highlights (основные достижения).
Некоторые выражения, которые помогут вам при составлении Key responsibilities и Highlights
(глагол / герундий или существительное):
To implement / implementation
To develop / development
To design / design
To devise / devising
To participate in… / participation in…
To assist smb in… / assisting smb in…
To represent smb or smth / representing smb or smth
To monitor / monitoring
To supervise / supervising
To create / creating, creation
To compile / compilation
Successfully
Effectively

** COMMENT Награды
** COMMENT Публикации
** COMMENT Членства в ассоциациях/организациях
** COMMENT Образование

Years attended
Bachelor’s degree in…
Master’s degree in…
PhD in…
Certificate in…
Specialist’s diploma in…
…(e.g. English philology) department


** COMMENT Дополнительные умения и навыки

Сюда входят языковые навыки (язык: уровень; к примеру, English: Advanced level), водительские
права, и т.п. Ключевые фразы:
Language skills
Elementary
Pre-intermediate
Intermediate
Upper-intermediate
Advanced
Native
Driving licence (BrE) или driver’s license (AmE)
Interests

** COMMENT Рекомендации
** COMMENT Работа, к которой я стремлюсь
** COMMENT Интересы

Travelling
Learning foreign languages
Dancing

** COMMENT Личная характеристика
