#+HTML: <h1>О сайте</h1>
#+HTML: <order>1</order>

#+STARTUP: showall indent hidestars

* О сайте

** Цель создания

Этот сайт был изначально создан для сбора редких и интересных
материалов о вычислительных моделях и языках
программирования. Позже он также превратился в занимательное
упражнение в реализации разнообразных программистких концепций.

** Исходный код

Исходный код открыт по лицензии GNU v.3. Данные, в том числе
руководства и книги, могут иметь свои лицензии.

Репозиторий с исходным кодом и историей коммитов доступен на
[[https://github.com/rigidus/rigidus.ru]]

Вы можете делать любые дополнения и предложения в форме
~pull-requests~ и ~issue~.

** Текущий статус

Отдельные вещи здесь переделываются прямо на ходу и кое-что может не работать по двум
причинам:
- Во-первых, я изменяю их, чтобы привести в соответствие с
  некоторым, постоянно изменяющимся ощущением "правильности".
- Во-вторых, отдельный части изменяются независимо от моей воли по
  сложным, часто недостаточно оттестированным экспериментальным
  алгоритмам, которые было бы безответственно запускать где-то еще.

  Если вы заметили ошибку или неточность - пожалуйста, сообщите мне
  об этом. Вы можете воспользоваться для этого способами, изложенными
  выше.

* Обо мне

** Личная информация

Меня зовут Глухов Михаил, я также известен как ~rigidus~. Этот ник
был выбран с целью упростить поиск в поисковых системах.

Я родился в 1982 году в г. Ленинград, теперь - Санкт-Петербург.

Мне можно в любой момент позвонить по телефону ~8(911)286-92-90~
или написать на ~i.am.rigidus at gmail dot com~

Я занимаюсь программированием и исследованиями в связанных
областях. Моя работа тоже имеет к этому самое прямое отношение.

Я накопил значитетельный опыт за это время и готов делиться
экспертизой.

** Исследовательский опыт

Я сделал несколько исследовательских работ (часть из которых еще не
завершена):
- Проверка корректности автоматных парсеров контекстно-свободных
  языков
- Верификация протоколов обмена сообщениями в распределенных сетях
- Создание языков предметной области систем автоматизированного
  принятия решений
- Автоматизация написания декомпиляторов для регисто-стековых
  виртуальных машин
- Построение и анализ средств визуального программирования для
  языков предметной области для систем реактивного управления
- Распределенные виртуальные машины с разделяемым состоянием

** COMMENT Работа, к которой я стремлюсь
** Опыт работы

#+HTML: <br />

#+NAME: work_expirience
#+BEGIN_SRC elisp :results output :exports results
     (defun job (&rest args)
       (let ((name         (plist-get args :name))
             (site         (plist-get args :site))
             (position     (plist-get args :position))
             (start-date   (plist-get args :start-date))
             (end-date     (plist-get args :end-date))
             (description  (plist-get args :description)))
         (when (string= "" end-date)
           (setq end-date "настоящее время"))
         (insert (format "\n#+HTML: <div class=\"workentry\">\n"))
         (insert (format "%s%s%s%s"
                         (format "\n#+HTML: <div class=\"workname\">\n%s\n#+HTML: </div>\n" name)
                         (format "\n#+HTML: <div class=\"worktime\">\n(c %s по %s)\n#+HTML: </div>\n" start-date end-date)
                         (format "\n#+HTML: <div class=\"workposition\">\n%s\n#+HTML: </div>\n" position)
                         (format "\n#+HTML: <div class=\"workdescr\">\n%s\n#+HTML: </div>\n" description)))
         (insert (format "\n#+HTML: </div>\n"))))

     (with-temp-file "work-expirience.org"
       (progn
         (job :name "ООО Автоматон"
              :site ""
              :position  "Руководитель разработки ПО, Системный архитектор"
              :start-date "2015-12-01"
              :end-date  ""
              :description "
         - Спроектировал программно-аппаратную архитектуру системы автоматизации платных парковок.
         - Спланировал и организовал работы по разработке ПО и аппаратной части, включая подбор электронных компонентов и схемотехническое проектирование.
         - Самостоятельно реализовал бизнес-логику и уровень представления (АРМ Оператора)
         - Руководил работами по реализации транспортного уровня и уровня абстракции оборудования, выполненными удаленными разработчиками.
         - Внедрил Continuous Integration и процесс управления жизненным циклом (релизы, исправление ошибок, добавление возможностей, технический контроль качества, автоматизированное тестирование)
         - Реализовал безопасное (цифровая подпись) и отказоустойчивое (откат на предыдующую версию при провале тестов) обновление прошивок через интернет.
         - Автоматизировал создание и хранение документации, с использованием версионирования на базе GIT и \"executable specifications\".")
         (job :name "ООО БКН"
              :site "http://bkn.ru"
              :position  "ИТ-директор"
              :start-date "2015-04-01"
              :end-date  "2015-12-01"
              :description "Руководил разработкой информационных решений автоматизации бизнеса агентств недвижимости (b2b и b2c). C# и ASP.NET")
         (job :name "Тренд"
              :site "http://trend-spb.ru"
              :position  "Ведущий инженер-программист"
              :start-date "2014-08-01"
              :end-date  "2015-03-01"
              :description "Автоматизировал бизнес-процесс агенства по продажам недвижимости (новостройки)")
         (job :name "Частная компания (алготрейдинг)"
              :site "http://aintsys.com"
              :position  "Lisp/Erlang-разработчик"
              :start-date "2012-04-01"
              :end-date  "2014-08-01"
              :description "Разрабатывал решения в сфере электронных валют")
         (job :name "ООО РАВТА"
              :site "http://ravta.ru"
              :position "Директор по IT"
              :start-date "2012-01-01"
              :end-date  "2012-04-01"
              :description "Осуществлял руководство разработкой информационной системы предприятия, занимался постановкой задач и контролем выполнения работ. Организовывал договорную работу с подрядчиками.")
         (job :name "WizardSoft"
              :site "http://wizardsoft.ru"
              :position "Ведущий разработчик, архитектор"
              :start-date "2011-05-01"
              :end-date "2012-01-01"
              :description "Разработка высоконагрузочного портала для проведения строительных тендеров. Прототип реализовал на Common Lisp, Postmodern и PostgreSQL. После приемки прототип был существенно расширен и переписан на PHP")
         (job :name "ЦиFры"
              :site "http://www.320-8080.ru"
              :position "Архитектор-проектировщик, веб-программист"
              :start-date "2009-09-01"
              :end-date "2011-04-01"
              :description "Перепроектировал и реализовал на высоконагрузочный интернет-магазин.
         Стек технологий: PHP, MySql, Jquery, Common Lisp, Memcached")
         (job :name "ООО Вебдом"
              :site  "http://webdom.net"
              :position "Ведущий веб-разработчик"
              :start-date "2007-01-01"
              :end-date "2009-09-01"
              :description "Cпроектировал и разработал масштабируемый фреймворк, на котором теперь работает компания. CMS на его основе поставляются клиентам.")
         (job :name "Почин"
              :site "http://pochin.ru"
              :position "Программист"
              :start-date "2005-09-01"
              :end-date "2007-01-01"
              :description "Спроектировал и разработал интернет-магазин на стеке технологий LAMP")))
#+END_SRC

#+INCLUDE: "other/work-expirience.org"

#+HTML: <br />

** COMMENT Награды
** COMMENT Публикации
** Членства в ассоциациях/организациях

Постоянный участник и докладчик семинаров по функциональному
программированию в Санкт-Петербурге [[https://plus.google.com/communities/106931692847918217517][fprog-community]] и
[[http://piter-united.ru][IT-Global-Meetup]]

** COMMENT Образование
** COMMENT Дополнительные умения и навыки
** COMMENT Рекомендации
** COMMENT Интересы
** COMMENT Личная характеристика
