#+HTML: <h1>Блог</h1>
#+HTML: <order>3</order>

-*- mode: org; fill-column: 95 -*-
@title Материалы по использованию Common Lisp

Здесь размещены тексты других лисперов, показавшиеся мне достаточно важными, чтобы на всякий
случай продублировать их. Разумеется, со ссылками на первоисточник, где могут быть ценные
комментарии.

* Common Lisp на практике

  @make-list-by-category ★ red cl @

* Устройство ASDF (linkfly)

  Исходный текст и комментарии: <a href="http://linkfly.livejournal.com/5582.html">http://linkfly.livejournal.com/5582.html</a>

  @make-list-by-category ★ green asdf @

* Скоро
<ul>
<li> <span style="color: green">★</span> Подсистема определения. UNION-OF-DEPENDENCIES</li>
<li> <span style="color: green">★</span> Подсистема загрузки. OPERATE</li>
<li> <span style="color: green">★</span> Подсистема загрузки. Подсистема планирования операций. TRAVERSE</li>
<li> <span style="color: green">★</span> Подсистема загрузки. Подсистема планирования операций. DO-TRAVERSE</li>
<li> <span style="color: green">★</span> Подсистема загрузки. Подсистема планирования операций. DO-DEP</li>
<li> <span style="color: green">★</span> Подсистема загрузки. MAKE-SUB-OPERATION</li>
<li> <span style="color: green">★</span> Подсистема загрузки. PERFORM-PLAN и PERFORM-WITH-RESTART</li>
<li> <span style="color: green">★</span> Подсистема загрузки. Подсистема выполнения операций. PERFORM</li>
<li> <span style="color: green">★</span> Подсистема загрузки. FIND-COMPONENT</li>
<li> <span style="color: green">★</span> Подсистема поиска. FIND-SYSTEM</li>
<li> <span style="color: green">★</span> Подсистема поиска. COMPUTE-SOURCE-REGISTRY</li>
<li> <span style="color: green">★</span> Подсистема поиска. RESOLVE-LOCATIO</li>
<li> <span style="color: green">★</span> Подсистема определения путей. INPUT-FILES, OUTPUT-FILES и COMPONENT-PATHNAME</li>
<li> <span style="color: green">★</span> Подсистема определения путей. APPLY-OUTPUT-TRANSLATIONS</li>
<li> <span style="color: green">★</span> Подсистема определения путей. COMPUTE-OUTPUT-TRANSLATIONS</li>
<li> <span style="color: green">★</span> Эпилог</li>
</ul>
