* About me

  Меня зовут =Михаил Rigidus Глухов=, я программист и системный
  архитектор. На этом сайте я собираю материалы по интересующим меня
  темам.

  Мне интересна теория языков программирования, алгоритмика,
  робототехника и все что связано с интернетом вещей.

* Автоматический поиск работы

  Все программисты ищут (или искали) работу на профильных сайтах и
  каждый из них хоть раз задумывался об автоматизации рутинных
  операций.

  Я решил пойти дальше и разработал экспертную систему с элементами
  искусственного интеллекта, которая ищет работу за меня в полностью
  автоматическом режиме - от подбора вакансий до автоматической
  адаптации резюме.

* Система автоматизации тестирования

  Однажды мне захотелось тестировать не только web но и gui-приложения
  и я решил написать маленький скрипт, способный действовать от имени
  пользователя, как если бы он сам манипулировал мышью и клавиатурой,
  считывая картинку на экране.

* Моделирование электронных схем

  Распространение сигнала внутри схемы дает возможность иначе
  взглянуть на процесс программирования и отладки и применить очень
  необычные и мощные идеи.

  Я написал язык предметной области (DSL) для построения схем и
  виртуальную машину в которой он исполняется, чтобы получать
  результаты распространения сигнала в моделируемой схеме.

  Однако этого оказалось недостаточно для обеспечения наглядности,
  поэтому я изучил Tcl/Tk и запрограммировал визуализатор
  распространения сигнала, чтобы прямо на экране видеть, как высокие и
  низкие уровни двигаются от одного элемента к другому.

* Умный гараж с нуля

  Не первый опыт в автоматике и робототехнике, но пожалуй первый
  настолько масштабный проект.

  Ядром системы является платформа BeagleBoneBlack, остальная часть
  большей частью самодельная, с помощью ЛУТ и гремучей смеси
  современных микроконтроллеров и старых советских комплектующих,
  найденных непонятно где.

  Содержит систему автономного питания, вентиляции, освещения
  электронный замок и видеоконтроль периметра с элементами машинного
  зрения. Планируется добавить систему сопротивления вторжению в виде
  пейнтбольного маркера с наведением на движуюся цель.

* Структура и интерпретация компьютерных программ (SICP)

  Материал этой книги был основой вводного курса по информатике в MIT
  начиная с 1980 года. К тому времени, как было выпущено первое
  издание, этот материал преподавался в течение четырех лет, и прошло
  еще двенадцать лет до появления второго издания.

  [[http://rigidus.ru/resources/sicp.pdf"][Структура и интерпретация компьютерных программ. Абельсон, Сассман (перевод: Ю. Бронников)]]

* Типы в языках программирования (TAPL)

  Книга о теории типов. Рассматриваются вопросы проверки и
  автоматического вывода типов в языках программирования со
  статической типизацией. Для каждой темы сначала дается теория, а
  затем приводится реализация на OCaml.

  TAPL — это, бесспорно, настоящий кладезь знаний для разработчиков
  языков программирования со статической типизацией.

  [[http://rigidus.ru/resources/tapl.pdf"][Типы в языках программирования. Бенджамин Пирс]]

* Литературное программирование

  Слайды с лекции "Грамотное программирование" (literate programming),
  которую я читал 22 января 2015 доступны
  [[http://slides.com/rigidusrigidus/deck#/"][http://slides.com/rigidusrigidus/deck/]]

* Макросы в Lisp

  Видео, с доклада на ноябрьском FProg Meetup "Макросы в лиспе"
  опубликовано на youtube: [[https://www.youtube.com/watch?v=i1lD2J7qLLM"][https://www.youtube.com/watch?v=i1lD2J7qLLM]]

* Как проектируются IP-блоки и системы на кристалле

  Юрий Панчул прочитал эту лекцию в Алма-Ате и я подготовил небольшой
  конспект. Осталось немного довести его до ума и я выложу его на
  сайт, а пока доступно [[https://www.youtube.com/watch?v=sPaMiEunT_M"][видео]], [[http://www.silicon-russia.com/public_materials/2016_09_01_kazakhstan/day_1_industry/03_slides/03_extra_eda_flow_2015_10_25.pdf"][слайды]] и его [[https://habrahabr.ru/post/309570/"][отчетный пост]] на хабре.
