#+STARTUP: showall indent hidestars
#+HTML_HEAD: <!-- -*- mode: org; fill-column: 87 -*-  -->

#+HTML_DOCTYPE: <!DOCTYPE html>
#+HTML_HEAD: <link href="css/style.css" rel="stylesheet" type="text/css" />

#+OPTIONS: toc:nil num:nil h:4 html-postamble:nil html-preamble:t tex:t f:t

#+TOC: headlines 3

#+HTML: <div class="outline-2" id="meta"><a href="index.html">На главную</a></div>

#+TITLE: Резюме

* ООО Автоматон
** Системный архитектор

|          c | по              |
| 2015-12-01 | настоящее время |

Компания занимается разработкой и эксплуатацией автоматизированных
парковок.

Я возглавил исследовательский проект по разработке новой парковочной
системы: аппаратной и программной части.

Технологии:
- Проектирование печатных плат - Kikad, Altium Designer
- Программирование: С/С++, Assembler, Erlang (телефония), PHP/JS:
  Symfony+React (веб-интерфейс), EmacsLisp - кодогенерация для
  "исполняемых спецификаций" и утилиты для совместной удаленной работы
  в команде
- Архитектурный стек - Linux on ARM Cortex A8 и Symphony+React в
  интерфейсе управления платной парковкой.

Разработку проводил с нуля, по этапам:
- Найм сотрудников
- Выбор электронных компонентов,
- Создание печатных плат,
- Написание низкоуровневого кода, управляющего шлагбаумами и
  опрашивающего датчики
- Написание бизнес-логики и веб-интерфейсов, через которые можно
  управлять парковкой удаленно,
- Подключение интернет-телефонии, для общения с клиентом в
  нестандартных ситуациях

Первое внедрение состоялось через полгода от начала разработки,
разработка полностью окупилась через год. Технологически разработанное
решение опережает конкурирующие. В том числе, по соотношению
цена/качество (но не в отношении пром-дизайна) - опережает даже
большинство зарубежных конкурентов.

Мои достижения:

- Спроектировал программно-аппаратную архитектуру системы
  автоматизации платных парковок.
- Спланировал и организовал работы по разработке ПО и аппаратной
  части, включая подбор электронных компонентов и схемотехническое
  проектирование.
- Самостоятельно реализовал бизнес-логику и уровень представления
  (Рабочее Место Оператора) на Symfony и React
- Руководил работами по реализации транспортного уровня и уровня
  абстракции оборудования, выполненными удаленными разработчиками
  (C/C++, модули ядра, драйверы устройств)
- Организовал паралельную разработку по модульному принципу (чтобы
  ускорить создание продукта) и методологии kanban
- Внедрил Continuous Integration и процесс управления жизненным циклом
  (релизы, исправление ошибок, добавление возможностей, технический
  контроль качества, автоматизированное тестирование)
- Реализовал безопасное (цифровая подпись) и отказоустойчивое (откат
  на предыдующую версию при провале тестов) обновление прошивок через
  интернет.
- Автоматизировал создание и хранение документации, с использованием
  версионирования на базе GIT и "executable specifications".

* ООО БКН
** ИТ-директор

|          c |         по |
| 2015-04-01 | 2015-12-01 |

Компания - второй после "Бюллетеня недвижимости" информационный
источник в области недвижимости по С-Пб и ЛО.

Руководил разработкой и продвижением информационных решений
автоматизации бизнеса агентств недвижимости (b2b и b2c).

Стек технологий: C# и ASP.NET, ExtJs

Достижения:

- Используя данные "межагентской БД bkn-profi" в короткие сроки создал
  раздел о жилых комплексах и новостройках, который по обьему вскоре
  достиг 60% сайта, что позволило резко увеличить доходы от рекламы на
  сайте.
- Реализовал на сайте bkn.ru раздел поиска и подбора квартир, комнат и
  жилых домов первичного и вторичного рынка, интегрировал его с
  межагентской БД объектов недвижимости.

* Тренд
** Ведущий инженер-программист

|          c |         по |
| 2014-08-01 | 2015-03-01 |

Компания - молодое быстрорастущее агенство недвижимости,
специализирующееся на первичном рынке (новостройки)

Автоматизировал бизнес-процесс агенства по продажам недвижимости
(новостройки).

Стек технологий: Php, Nginx, Mysql, PostgreSql

Достижения:

До моего прихода агенты и риэлторы использовали skype и google docs
для выполнения задач, но после увеличения численности в 4 раза эти
инструменты стали неэффективны. Я внедрил CRM собственной разработки,
модули которой (экспертная система выставления цен, интерактивный
подбор объектов) освободили работников от рутины.

Также реорганизовал сайт компании с использованием современных
технологий.

* Частная компания (алготрейдинг)
** Lisp/Erlang-разработчик

|          с |         по |
| 2012-04-01 | 2014-08-01 |

Стек технологий: Erlang, Common Lisp, C++

К сожалению, по условиям NDA я не имею права распространять в сети
информацию о деятельности компании и моих разработках :(

* ООО РАВТА
** Технический директор

|          с |         по |
| 2012-01-01 | 2012-04-01 |

Осуществлял руководство разработкой информационной системы
предприятия, занимался |становкой задач и контролем вы|лнения
работ. Организовывал договорную работу с |дрядчиками.

Компания - интернет-магазин запчастей, комплектующих и расходных
материалов для автомобилей.

Осуществлял руководство разработкой информационной системы
предприятия, занимался постановкой задач и контролем выполнения
работ. Организовывал договорную работу с подрядчиками.

Достижения:

Внедрил на фирме 1-С Предприятие и 1С-Склад и обеспечил ее интеграцию
с системой TechDoc.

* WizardSoft
** Ведущий разработчик, архитектор

|          с |         по |
| 2011-05-01 | 2012-01-01 |

Компания занимается автоматизацией управления затратами в
стоительстве.
Достижения:

Разработал высоконагрузочный портал для проведения строительных
тендеров. Прототип реализовал на Common Lisp, Postmodern и
PostgreSQL. После приемки прототип был существенно расширен и
переписан на PHP

* ЦиFры
** Архитектор-проектировщик, веб-программист

|          с |         по |
| 2009-09-01 | 2011-04-01 |

Компания - интернет-магазин цифровой техники.

Стек технологий: PHP, MySql, Jquery, Common Lisp, Memcached

Достижения:

- На первом этапе в кратчайшие сроки подготовил legacy-код к
  новогодним нагрузкам путем внедрения кэширования.
- Затема полностью перепроектировал и реализовал на высоконагрузочный
  интернет-магазин.


* ООО Вебдом
** Ведущий веб-разработчик

|          с |         по |
| 2007-01-01 | 2009-09-01 |

Веб-студия
Стек технологий: Php, Nginx, MySql

Достижения:

Cпроектировал и разработал масштабируемый фреймворк, на котором теперь
работает компания. CMS на его основе поставляются клиентам.

* Почин
** Программист

|          с |         по |
| 2005-09-01 | 2007-01-01 |

Компания - интернет-магазин авточехлов, автозапчастей и
автоинструмента.

Стек технологий: LAMP

Первоначально начинал как фриланс-программист, но скоро сотрудничество
стало постоянным.

Достижения:

- Спроектировал и разработал интернет-магазин (три версии за полтора года)
