#+STARTUP: showall indent hidestars

#+HTML_HEAD: <!-- -*- fill-column: 87 -*- -->
#+HTML_HEAD: <!-- org-toggle-inline-images -->

#+TITLE: О сайте

#+INFOJS_OPT: view:overview toc:nil

#+NAME:css
#+BEGIN_HTML
<link rel="stylesheet" type="text/css" href="/css/css.css" />
#+END_HTML


* Цель создания

Этот сайт был изначально создан для сбора редких и интересных
материалов о вычислительных моделях и языках
программирования. Позже он также превратился в занимательное
упражнение в реализации разнообразных программистких концепций.

* Исходный код

Исходный код открыт по лицензии GNU v.3. Данные, в том числе
руководства и книги, могут иметь свои лицензии.

Репозиторий с исходным кодом и историей коммитов доступен на
[[https://github.com/rigidus/rigidus.ru]]

Вы можете делать любые дополнения и предложения в форме
~pull-requests~ и ~issue~.

* Текущий статус

Отдельные вещи здесь переделываются прямо на ходу и кое-что может не работать по двум
причинам:
- Я изменяю их, чтобы привести в соответствие с некоторым, постоянно
  изменяющимся ощущением "правильности".
- Отдельный части изменяются независимо от моей воли по сложным, часто
  недостаточно оттестированным экспериментальным алгоритмам, которые
  было бы безответственно запускать где-то еще.

  Если вы заметили ошибку или неточность - пожалуйста, сообщите мне
  об этом. Вы можете воспользоваться для этого способами, изложенными
  выше.

* Как это работает

О том как все это устроено можно почитать в соответствующем разделе [TODO:gmm]
