#+STARTUP: showall indent hidestars
#+HTML_HEAD: <!-- -*- mode: org; fill-column: 87 -*-  -->

#+HTML_DOCTYPE: <!DOCTYPE html>
#+HTML_HEAD: <link href="css/style.css" rel="stylesheet" type="text/css" />

#+OPTIONS: toc:nil num:nil h:4 html-postamble:nil html-preamble:t tex:t f:t

#+TOC: headlines 3

#+HTML: <div class="outline-2" id="meta"><a href="index.html">На главную</a></div>

#+TITLE: О сайте

* Цель создания

Этот сайт был изначально создан для сбора редких и интересных
материалов о вычислительных моделях и языках программирования. Позже
он также превратился в занимательное упражнение в реализации
разнообразных программистких концепций.

* Исходный код

Исходный код открыт по лицензии GNU v.3. Данные, в том числе
руководства и книги, могут иметь свои лицензии.

Репозиторий с исходным кодом и историей коммитов доступен на
[[https://github.com/rigidus/rigidus.ru]]

Вы можете делать любые дополнения и предложения в форме
~pull-requests~ и ~issue~.

* Текущий статус

Отдельные вещи здесь переделываются прямо на ходу и кое-что может не
работать, потому что я постоянно изменяю их, чтобы привести в
соответствие с некоторым, постоянно изменяющимся ощущением
"правильности".

Если вы заметили ошибку или неточность - пожалуйста, сообщите мне об
этом.
